// app/me/profile.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { LinearGradient } from 'expo-linear-gradient';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { Controller, useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { AppHeader, Screen } from '../../src/components/layout';
import { EmptyState, ErrorState, Skeleton, useToast } from '../../src/components/feedback';
import { AvatarFrame, Tag } from '../../src/components/ui';
import { UserRepo } from '../../src/repos';
import { useAuthStore } from '../../src/store';
import { useTheme } from '../../src/theme';
import { AppError, UserProfile } from '../../src/types';

const profileSchema = z.object({
  name: z.string().min(2, '昵称至少 2 个字').max(12, '昵称不超过 12 个字'),
  location: z.string().min(2, '请填写所在地').max(20, '所在地不超过 20 个字'),
  interests: z.string().optional(),
});

type ProfileFormValues = z.infer<typeof profileSchema>;

const parseInterests = (value: string) =>
  value
    .split(/[,，、/\s]+/)
    .map((item) => item.trim())
    .filter((item) => item.length > 0)
    .slice(0, 6);

const formatInterests = (interests?: string[]) => (interests && interests.length > 0 ? interests.join('、') : '');

export default function MeProfileScreen() {
  const { colors, radius, shadow, spacing, typography } = useTheme();
  const { show } = useToast();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [refreshing, setRefreshing] = useState(false);
  const isLoggedIn = useAuthStore((state) => state.isLoggedIn);

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['me-profile-detail'],
    queryFn: () => UserRepo.profile(),
    enabled: isLoggedIn,
  });

  const profile = data?.ok ? data.data : null;
  const error = data && !data.ok ? data.error : null;

  const { control, handleSubmit, reset, watch, formState } = useForm<ProfileFormValues>({
    resolver: zodResolver(profileSchema),
    defaultValues: {
      name: '',
      location: '',
      interests: '',
    },
  });

  useEffect(() => {
    if (!profile) {
      return;
    }
    reset({
      name: profile.name,
      location: profile.location,
      interests: formatInterests(profile.interests),
    });
  }, [profile, reset]);

  const watchedInterests = watch('interests') ?? '';
  const interestTags = useMemo(() => parseInterests(watchedInterests), [watchedInterests]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await refetch();
    setRefreshing(false);
  };

  const handleReset = (dataToReset: UserProfile) => {
    reset({
      name: dataToReset.name,
      location: dataToReset.location,
      interests: formatInterests(dataToReset.interests),
    });
  };

  const handleSave = async (values: ProfileFormValues) => {
    const result = await UserRepo.updateProfile({
      name: values.name.trim(),
      location: values.location.trim(),
      interests: parseInterests(values.interests ?? ''),
    });
    if (!result.ok) {
      show({ message: result.error.displayMessage ?? '保存失败', type: 'error' });
      return;
    }
    show({ message: '资料已更新', type: 'success' });
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['me-profile'] }),
      queryClient.invalidateQueries({ queryKey: ['me-profile-detail'] }),
      queryClient.invalidateQueries({ queryKey: ['me-vip-profile'] }),
      queryClient.invalidateQueries({ queryKey: ['userProfile'] }),
    ]);
    handleReset(result.data);
  };

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="个人资料" />
      {isLoading ? (
        <View style={{ padding: spacing.xl }}>
          <Skeleton height={160} radius={radius.lg} />
          <View style={{ height: spacing.md }} />
          <Skeleton height={220} radius={radius.lg} />
        </View>
      ) : error ? (
        <View style={{ padding: spacing.xl }}>
          <ErrorState
            title="资料加载失败"
            description={(error as AppError)?.displayMessage ?? '请稍后重试'}
            onAction={refetch}
          />
        </View>
      ) : !profile ? (
        <View style={{ padding: spacing.xl }}>
          <EmptyState title="暂无资料" description="请稍后再试" />
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
        >
          {/* 头像区域 */}
          <Animated.View entering={FadeInDown.duration(300)}>
            <View style={[styles.card, shadow.md, { backgroundColor: colors.surface, borderRadius: radius.lg }]}>
              <View style={styles.row}>
                <Pressable onPress={() => router.push('/me/appearance')}>
                  <AvatarFrame uri={profile.avatar} size={72} frame={profile.avatarFrame} />
                </Pressable>
                <View style={{ flex: 1, marginLeft: 12 }}>
                  <Text style={[typography.title3, { color: colors.text.primary }]}>{profile.name}</Text>
                  <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 4 }]}>{profile.location}</Text>
                  <View style={styles.tagRow}>
                    {(profile.interests ?? []).slice(0, 3).map((tag) => (
                      <Tag key={tag} label={tag} tone="neutral" style={{ marginRight: 6, marginTop: 6 }} />
                    ))}
                  </View>
                </View>
                <Pressable
                  onPress={() => router.push('/me/appearance')}
                  style={[styles.action, { borderColor: colors.border, borderRadius: radius.pill }]}
                >
                  <Text style={[typography.caption, { color: colors.text.secondary }]}>装扮</Text>
                </Pressable>
              </View>
            </View>
          </Animated.View>

          {/* 偏好与信息 */}
          <Animated.View entering={FadeInDown.duration(300).delay(80)}>
            <View style={{ marginTop: spacing.lg }}>
              <Text style={[typography.title3, { color: colors.text.primary }]}>偏好与信息</Text>
              <View style={[styles.card, shadow.md, { backgroundColor: colors.surface, borderRadius: radius.lg }]}>
                <View style={styles.field}>
                  <Text style={[typography.caption, { color: colors.text.secondary }]}>昵称</Text>
                  <Controller
                    control={control}
                    name="name"
                    render={({ field: { value, onChange } }) => (
                      <TextInput
                        value={value}
                        onChangeText={onChange}
                        placeholder="请输入昵称"
                        placeholderTextColor={colors.text.secondary}
                        style={[styles.input, { borderColor: colors.border, color: colors.text.primary, backgroundColor: colors.surface }]}
                      />
                    )}
                  />
                  {formState.errors.name ? (
                    <Text style={[typography.caption, { color: colors.danger }]}>
                      {formState.errors.name.message}
                    </Text>
                  ) : null}
                </View>

                <View style={styles.field}>
                  <Text style={[typography.caption, { color: colors.text.secondary }]}>所在地</Text>
                  <Controller
                    control={control}
                    name="location"
                    render={({ field: { value, onChange } }) => (
                      <TextInput
                        value={value}
                        onChangeText={onChange}
                        placeholder="例如：上海"
                        placeholderTextColor={colors.text.secondary}
                        style={[styles.input, { borderColor: colors.border, color: colors.text.primary, backgroundColor: colors.surface }]}
                      />
                    )}
                  />
                  {formState.errors.location ? (
                    <Text style={[typography.caption, { color: colors.danger }]}>
                      {formState.errors.location.message}
                    </Text>
                  ) : null}
                </View>

                <View style={styles.field}>
                  <Text style={[typography.caption, { color: colors.text.secondary }]}>兴趣标签</Text>
                  <Controller
                    control={control}
                    name="interests"
                    render={({ field: { value, onChange } }) => (
                      <TextInput
                        value={value}
                        onChangeText={onChange}
                        placeholder="用逗号分隔，例如：有机蔬菜、蓝莓"
                        placeholderTextColor={colors.text.secondary}
                        style={[styles.input, { borderColor: colors.border, color: colors.text.primary, backgroundColor: colors.surface }]}
                      />
                    )}
                  />
                  {/* 兴趣标签 — 选中态微渐变 */}
                  <View style={styles.tagRow}>
                    {interestTags.map((tag) => (
                      <View key={tag} style={[styles.interestTag, { overflow: 'hidden', borderRadius: radius.pill }]}>
                        <LinearGradient
                          colors={[colors.brand.primarySoft, colors.ai.soft]}
                          start={{ x: 0, y: 0 }}
                          end={{ x: 1, y: 0 }}
                          style={{ paddingHorizontal: 10, paddingVertical: 4 }}
                        >
                          <Text style={[typography.caption, { color: colors.brand.primary }]}>{tag}</Text>
                        </LinearGradient>
                      </View>
                    ))}
                  </View>
                  <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 4 }]}>
                    最多展示 6 个标签
                  </Text>
                </View>

                {/* 保存按钮 */}
                <Pressable
                  onPress={handleSubmit(handleSave)}
                  disabled={!formState.isDirty || formState.isSubmitting}
                >
                  <LinearGradient
                    colors={!formState.isDirty ? [colors.border, colors.border] : [colors.brand.primary, colors.ai.start]}
                    start={{ x: 0, y: 0 }}
                    end={{ x: 1, y: 0 }}
                    style={[styles.primary, { borderRadius: radius.pill, marginTop: 14 }]}
                  >
                    <Text
                      style={[
                        typography.bodyStrong,
                        { color: !formState.isDirty ? colors.text.secondary : colors.text.inverse },
                      ]}
                    >
                      保存修改
                    </Text>
                  </LinearGradient>
                </Pressable>
                <Pressable
                  onPress={() => handleReset(profile)}
                  style={[styles.secondary, { borderColor: colors.border, borderRadius: radius.pill }]}
                >
                  <Text style={[typography.bodyStrong, { color: colors.text.secondary }]}>重置</Text>
                </Pressable>
              </View>
            </View>
          </Animated.View>
        </ScrollView>
      )}
    </Screen>
  );
}

const styles = StyleSheet.create({
  card: {
    padding: 16,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  interestTag: {
    marginRight: 6,
    marginTop: 6,
  },
  action: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  field: {
    marginBottom: 14,
  },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
  },
  primary: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  secondary: {
    marginTop: 10,
    alignItems: 'center',
    paddingVertical: 10,
    borderWidth: 1,
  },
});

// 交付包/uniapp/src/pages-sub/me/profile.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="个人资料" />
    <view v-if="loading" class="nm-loading">
      <Skeleton :count="2" type="card" />
    </view>
    <view v-else-if="errorMessage" class="nm-loading">
      <ErrorState :text="errorMessage" @retry="fetchProfile" />
    </view>
    <view v-else-if="!profile" class="nm-loading">
      <EmptyState text="暂无资料" hint="请稍后再试" />
    </view>
    <scroll-view
      v-else
      class="nm-page"
      scroll-y
      refresher-enabled
      :refresher-triggered="refreshing"
      @refresherrefresh="onRefresh"
    >
      <view class="nm-card">
        <view class="nm-row">
          <view @click="goAppearance">
            <AvatarFrame :uri="profile?.avatar" :frame="profile?.avatarFrame" :size="72" />
          </view>
          <view class="nm-user-info">
            <text class="nm-user-name">{{ profile?.name }}</text>
            <text class="nm-user-meta">{{ profile?.location }}</text>
            <view class="nm-tag-row">
              <view v-for="tag in (profile?.interests || []).slice(0, 3)" :key="tag" class="nm-tag-wrap">
                <Tag :label="tag" tone="neutral" />
              </view>
            </view>
          </view>
          <view class="nm-action" @click="goAppearance">装扮</view>
        </view>
      </view>

      <view class="nm-section">
        <text class="nm-section-title">偏好与信息</text>
        <view class="nm-card">
          <view class="nm-field">
            <text class="nm-label">昵称</text>
            <input
              class="nm-input"
              v-model="form.name"
              placeholder="请输入昵称"
              placeholder-class="nm-placeholder"
              @input="clearError('name')"
            />
            <text v-if="errors.name" class="nm-error">{{ errors.name }}</text>
          </view>
          <view class="nm-field">
            <text class="nm-label">所在地</text>
            <input
              class="nm-input"
              v-model="form.location"
              placeholder="例如：上海"
              placeholder-class="nm-placeholder"
              @input="clearError('location')"
            />
            <text v-if="errors.location" class="nm-error">{{ errors.location }}</text>
          </view>
          <view class="nm-field">
            <text class="nm-label">兴趣标签</text>
            <input
              class="nm-input"
              v-model="form.interests"
              placeholder="用逗号分隔，例如：有机蔬菜、蓝莓"
              placeholder-class="nm-placeholder"
              @input="clearError('interests')"
            />
            <view class="nm-tag-row">
              <view v-for="tag in interestTags" :key="tag" class="nm-tag-wrap">
                <Tag :label="tag" tone="neutral" />
              </view>
            </view>
            <text class="nm-tip">最多展示 6 个标签</text>
          </view>
          <view
            :class="['nm-primary', !isDirty || saving ? 'nm-primary--disabled' : '']"
            @click="saveProfile"
          >
            {{ saving ? '保存中...' : '保存修改' }}
          </view>
          <view class="nm-secondary" @click="resetProfile">重置</view>
        </view>
      </view>
    </scroll-view>
  </Screen>
</template>

<script setup lang="ts">
import { navTo } from '@/utils/nav';
import { reactive, ref, computed } from 'vue';
import { Screen, AppHeader, Skeleton, ErrorState, EmptyState, AvatarFrame, Tag } from '@/components';
import { UserRepo, type UserProfile } from '@/services/repos';

const profile = ref<UserProfile | null>(null);
const loading = ref(true);
const saving = ref(false);
const errorMessage = ref('');
const refreshing = ref(false);
const initialSnapshot = ref({ name: '', location: '', interests: '' });

const form = reactive({
  name: '',
  location: '',
  interests: '',
});

const errors = reactive({
  name: '',
  location: '',
  interests: '',
});

const parseInterests = (value: string) =>
  value
    .split(/[,，、/\s]+/)
    .map((item) => item.trim())
    .filter((item) => item.length > 0)
    .slice(0, 6);

const interestTags = computed(() => parseInterests(form.interests));

const isDirty = computed(() => {
  return (
    form.name.trim() !== initialSnapshot.value.name ||
    form.location.trim() !== initialSnapshot.value.location ||
    form.interests.trim() !== initialSnapshot.value.interests
  );
});

const clearError = (field: 'name' | 'location' | 'interests') => {
  errors[field] = '';
};

const applyProfile = (data: UserProfile) => {
  profile.value = data;
  form.name = data.name || '';
  form.location = data.location || '';
  form.interests = (data.interests || []).join('、');
  initialSnapshot.value = {
    name: form.name,
    location: form.location,
    interests: form.interests,
  };
};

const fetchProfile = async () => {
  loading.value = true;
  const res = await UserRepo.profile();
  if (res.ok) {
    errorMessage.value = '';
    applyProfile(res.data);
  } else {
    errorMessage.value = res.error.message || '加载失败';
  }
  loading.value = false;
};

const onRefresh = async () => {
  if (refreshing.value) return;
  refreshing.value = true;
  await fetchProfile();
  refreshing.value = false;
};

const validate = () => {
  errors.name = '';
  errors.location = '';
  errors.interests = '';
  if (form.name.trim().length < 2) {
    errors.name = '昵称至少 2 个字';
  } else if (form.name.trim().length > 12) {
    errors.name = '昵称不超过 12 个字';
  }
  if (form.location.trim().length < 2) {
    errors.location = '请填写所在地';
  } else if (form.location.trim().length > 20) {
    errors.location = '所在地不超过 20 个字';
  }
  return !errors.name && !errors.location;
};

const saveProfile = async () => {
  if (!isDirty.value || saving.value) return;
  if (!validate()) return;
  saving.value = true;
  const res = await UserRepo.updateProfile({
    name: form.name.trim(),
    location: form.location.trim(),
    interests: parseInterests(form.interests),
  });
  saving.value = false;
  if (res.ok) {
    applyProfile(res.data);
    uni.showToast({ title: '资料已更新', icon: 'success' });
  } else {
    uni.showToast({ title: res.error.message || '保存失败', icon: 'none' });
  }
};

const resetProfile = () => {
  if (!profile.value) return;
  form.name = initialSnapshot.value.name;
  form.location = initialSnapshot.value.location;
  form.interests = initialSnapshot.value.interests;
  errors.name = '';
  errors.location = '';
  errors.interests = '';
};

const goAppearance = () => {
  navTo({ url: '/pages-sub/me/appearance' });
};

fetchProfile();
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-loading {
  padding: $nm-space-xl;
}

.nm-card {
  padding: $nm-space-lg;
  border-radius: $nm-radius-lg;
  background-color: $nm-surface;
  box-shadow: $nm-shadow-sm;
  border: 1rpx solid transparent;
}

.nm-section {
  margin-top: $nm-space-lg;
}

.nm-row {
  display: flex;
  flex-direction: row;
  align-items: center;
}

.nm-user-info {
  flex: 1;
  margin-left: $nm-space-sm;
}

.nm-user-name {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-user-meta {
  margin-top: 8rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-tag-row {
  margin-top: 12rpx;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.nm-tag-wrap {
  margin-right: 12rpx;
  margin-top: 12rpx;
}

.nm-action {
  padding: 12rpx 20rpx;
  border-radius: $nm-radius-pill;
  border: 1rpx solid $nm-border;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-section-title {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
  margin-bottom: 0;
}

.nm-field {
  margin-bottom: 28rpx;
}

.nm-label {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-input {
  margin-top: 6rpx;
  border-radius: $nm-radius-md;
  background-color: $nm-surface;
  border: 1rpx solid $nm-border;
  padding: 20rpx 24rpx;
  color: $nm-text-primary;
}

.nm-placeholder {
  color: $nm-muted;
}

.nm-error {
  margin-top: 6rpx;
  font-size: $nm-font-caption;
  color: $nm-danger;
}

.nm-tip {
  margin-top: 6rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-primary {
  margin-top: 28rpx;
  padding: 20rpx 0;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary;
  text-align: center;
  color: $nm-text-inverse;
  font-weight: 600;
}

.nm-primary--disabled {
  background-color: $nm-border;
  color: $nm-text-secondary;
}

.nm-secondary {
  margin-top: 20rpx;
  padding: 20rpx 0;
  border-radius: $nm-radius-pill;
  border: 1rpx solid $nm-border;
  text-align: center;
  color: $nm-text-secondary;
  font-weight: 600;
}
</style>
