// 交付包/爱买买-前端源码/app/settings.tsx
import React, { useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { AppHeader, Screen } from '../src/components/layout';
import { useToast } from '../src/components/feedback';
import { useTheme } from '../src/theme';

export default function SettingsScreen() {
  const { colors, radius, shadow, spacing, typography } = useTheme();
  const { show } = useToast();
  const router = useRouter();
  const [refreshing, setRefreshing] = useState(false);
  const handleRefresh = async () => {
    setRefreshing(true);
    await new Promise((resolve) => setTimeout(resolve, 300));
    setRefreshing(false);
  };

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="设置" />
      <ScrollView
        contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
      >
        <View style={[styles.sectionCard, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}>
          <Text style={[typography.title3, { color: colors.text.primary }]}>账号与安全</Text>
          <Pressable
            onPress={() => show({ message: '账号与安全功能待接入', type: 'info' })}
            style={[styles.row, { borderBottomColor: colors.border }]}
          >
            <MaterialCommunityIcons name="account-lock-outline" size={18} color={colors.text.secondary} />
            <Text style={[typography.body, { color: colors.text.primary, marginLeft: spacing.sm }]}>账号与安全</Text>
            <View style={styles.spacer} />
            <MaterialCommunityIcons name="chevron-right" size={18} color={colors.text.secondary} />
          </Pressable>
          <Pressable
            onPress={() => show({ message: '通知设置待接入', type: 'info' })}
            style={styles.row}
          >
            <MaterialCommunityIcons name="bell-outline" size={18} color={colors.text.secondary} />
            <Text style={[typography.body, { color: colors.text.primary, marginLeft: spacing.sm }]}>通知设置</Text>
            <View style={styles.spacer} />
            <MaterialCommunityIcons name="chevron-right" size={18} color={colors.text.secondary} />
          </Pressable>
        </View>

        <View style={[styles.sectionCard, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg, marginTop: spacing.lg }]}>
          <Text style={[typography.title3, { color: colors.text.primary }]}>隐私与合规</Text>
          <Pressable
            onPress={() => router.push('/privacy')}
            style={[styles.row, { borderBottomColor: colors.border }]}
          >
            <MaterialCommunityIcons name="shield-lock-outline" size={18} color={colors.text.secondary} />
            <Text style={[typography.body, { color: colors.text.primary, marginLeft: spacing.sm }]}>隐私政策</Text>
            <View style={styles.spacer} />
            <MaterialCommunityIcons name="chevron-right" size={18} color={colors.text.secondary} />
          </Pressable>
          <Pressable onPress={() => router.push('/about')} style={styles.row}>
            <MaterialCommunityIcons name="information-outline" size={18} color={colors.text.secondary} />
            <Text style={[typography.body, { color: colors.text.primary, marginLeft: spacing.sm }]}>关于爱买买</Text>
            <View style={styles.spacer} />
            <MaterialCommunityIcons name="chevron-right" size={18} color={colors.text.secondary} />
          </Pressable>
        </View>

        <View style={{ marginTop: spacing.lg }}>
          <Pressable
            onPress={() => show({ message: '帮助与反馈待接入', type: 'info' })}
            style={[styles.helpCard, { borderColor: colors.border, borderRadius: radius.lg }]}
          >
            <MaterialCommunityIcons name="lifebuoy" size={18} color={colors.text.secondary} />
            <Text style={[typography.body, { color: colors.text.secondary, marginLeft: spacing.sm }]}>帮助与反馈</Text>
          </Pressable>
        </View>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  sectionCard: {
    padding: 14,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  spacer: {
    flex: 1,
  },
  helpCard: {
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
});

// 交付包/uniapp/src/pages-sub/me/settings.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="设置" />
    <scroll-view
      class="nm-page"
      scroll-y
      refresher-enabled
      :refresher-triggered="refreshing"
      @refresherrefresh="onRefresh"
    >
      <view class="nm-section">
        <view class="nm-card">
          <text class="nm-card__title">账号与安全</text>
          <view class="nm-row" @click="showInfo('账号与安全功能待接入')">
            <Icon class="nm-row__icon" name="account-lock-outline" :size="36" :color="textSecondary" />
            <text class="nm-row__label">账号与安全</text>
            <Icon class="nm-row__arrow" name="chevron-right" :size="36" :color="textSecondary" />
          </view>
          <view class="nm-row" @click="showInfo('通知设置待接入')">
            <Icon class="nm-row__icon" name="bell-outline" :size="36" :color="textSecondary" />
            <text class="nm-row__label">通知设置</text>
            <Icon class="nm-row__arrow" name="chevron-right" :size="36" :color="textSecondary" />
          </view>
        </view>
      </view>

      <view class="nm-section">
        <view class="nm-card">
          <text class="nm-card__title">隐私与合规</text>
          <view class="nm-row" @click="goPrivacy">
            <Icon class="nm-row__icon" name="shield-lock-outline" :size="36" :color="textSecondary" />
            <text class="nm-row__label">隐私政策</text>
            <Icon class="nm-row__arrow" name="chevron-right" :size="36" :color="textSecondary" />
          </view>
          <view class="nm-row" @click="goAbout">
            <Icon class="nm-row__icon" name="information-outline" :size="36" :color="textSecondary" />
            <text class="nm-row__label">关于农脉</text>
            <Icon class="nm-row__arrow" name="chevron-right" :size="36" :color="textSecondary" />
          </view>
        </view>
      </view>

      <view class="nm-help" @click="goHelp">
        <Icon class="nm-help__icon" name="lifebuoy" :size="36" :color="textSecondary" />
        <text class="nm-help__text">帮助与反馈</text>
      </view>
    </scroll-view>
  </Screen>
</template>

<script setup lang="ts">
import { navTo } from '@/utils/nav';
import { ref } from 'vue';
import { Screen, AppHeader, Icon } from '@/components';

const textSecondary = '#4B5B53';
const refreshing = ref(false);

const onRefresh = () => {
  if (refreshing.value) return;
  refreshing.value = true;
  setTimeout(() => {
    refreshing.value = false;
  }, 300);
};

const showInfo = (message: string) => {
  uni.showToast({ title: message, icon: 'none' });
};

const goPrivacy = () => {
  navTo({ url: '/pages-sub/me/privacy' });
};

const goAbout = () => {
  navTo({ url: '/pages-sub/me/about' });
};

const goHelp = () => {
  navTo({ url: '/pages-sub/me/help' });
};
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-section {
  margin-bottom: $nm-space-lg;
}

.nm-card {
  border-radius: $nm-radius-lg;
  background-color: $nm-surface;
  box-shadow: $nm-shadow-sm;
  border: 1rpx solid transparent;
  padding: 28rpx;
}

.nm-card__title {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-row {
  display: flex;
  flex-direction: row;
  align-items: center;
  padding: 24rpx 0;
  border-bottom: 1rpx solid $nm-border;
}

.nm-row__icon {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: $nm-space-sm;
}

.nm-row:last-child {
  border-bottom: none;
}

.nm-row__label {
  font-size: $nm-font-body;
  line-height: $nm-line-body;
  color: $nm-text-primary;
  flex: 1;
}

.nm-row__arrow {
  color: $nm-text-secondary;
  margin-left: auto;
  flex-shrink: 0;
}

.nm-help {
  padding: 24rpx 28rpx;
  border-radius: $nm-radius-lg;
  border: 1rpx solid $nm-border;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: flex-start;
  margin-top: $nm-space-lg;
}

.nm-help__icon {
  margin-right: $nm-space-sm;
}

.nm-help__text {
  font-size: $nm-font-body;
  color: $nm-text-secondary;
}
</style>
