// 交付包/uniapp/src/components/cards/PostCard.vue
<template>
  <view class="nm-post" @click="emitPress">
    <view class="nm-post__header">
      <view class="nm-post__author" @click.stop="emitAuthor">
        <view class="nm-post__avatar" />
        <view class="nm-post__author-info">
          <view class="nm-post__name-row">
            <text class="nm-post__name" number-of-lines="1">{{ authorName }}</text>
            <Icon v-if="isCompany" class="nm-post__verify" name="check-decagram" :size="28" :color="accentBlue" />
          </view>
          <text class="nm-post__meta" number-of-lines="1">{{ authorTag }}</text>
          <view v-if="item.followed && item.intimacyLevel" class="nm-post__intimacy">
            <text class="nm-post__intimacy-text">亲密度 {{ item.intimacyLevel }}%</text>
            <view class="nm-post__intimacy-track">
              <view class="nm-post__intimacy-fill" :style="{ width: `${item.intimacyLevel}%` }" />
            </view>
          </view>
        </view>
      </view>
      <view class="nm-post__header-actions">
        <view
          v-if="showFollow"
          :class="['nm-post__follow', item.followed ? 'nm-post__follow--active' : '']"
          @click.stop="emitFollow"
        >
          <text :class="['nm-post__follow-text', item.followed ? 'nm-post__follow-text--active' : '']">
            {{ item.followed ? '已关注' : '关注' }}
          </text>
        </view>
        <view class="nm-post__more" @click.stop="emitMore">
          <Icon class="nm-post__more-icon" name="dots-horizontal" :size="36" :color="textSecondary" />
        </view>
      </view>
    </view>

    <view class="nm-post__media">
      <image v-if="coverImage" :src="coverImage" class="nm-post__media-image" mode="aspectFill" />
      <view v-else class="nm-post__media-image nm-post__media-image--empty" />
      <view v-if="imageCount > 1" class="nm-post__image-count">
        <text class="nm-post__image-count-text">+{{ imageCount - 1 }}</text>
      </view>
      <view v-if="item.productId" class="nm-post__product-tag" @click.stop="emitProduct">
        <text class="nm-post__product-tag-text">{{ item.productTagLabel || '即看即买' }}</text>
      </view>
    </view>

    <text class="nm-post__title" number-of-lines="2">{{ item.title }}</text>
    <text class="nm-post__content" number-of-lines="3">{{ item.content }}</text>

    <view v-if="item.tags && item.tags.length" class="nm-post__tags">
      <view v-for="tag in item.tags" :key="tag" class="nm-tag">
        <text class="nm-tag__text">{{ tag }}</text>
      </view>
    </view>

    <view class="nm-post__footer">
      <text class="nm-post__time">{{ item.createdAt || '刚刚' }}</text>
      <view class="nm-post__actions">
        <view class="nm-post__action" @click.stop="emitLike">
          <Icon
            class="nm-post__action-icon"
            :name="liked ? 'heart' : 'heart-outline'"
            :size="36"
            :color="liked ? dangerColor : textSecondary"
          />
          <text class="nm-post__action-text">{{ item.likes || 0 }}</text>
        </view>
        <view class="nm-post__action" @click.stop="emitComment">
          <Icon class="nm-post__action-icon" name="comment-processing-outline" :size="36" :color="textSecondary" />
          <text class="nm-post__action-text">{{ item.comments || 0 }}</text>
        </view>
        <view class="nm-post__action" @click.stop="emitShare">
          <Icon class="nm-post__action-icon" name="share-variant" :size="36" :color="textSecondary" />
          <text class="nm-post__action-text">{{ item.shares || 0 }}</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Icon from '@/components/ui/Icon.vue';

const props = withDefaults(
  defineProps<{
    item: Record<string, any>;
    currentUserId?: string;
  }>(),
  {
    currentUserId: '',
  }
);

const emit = defineEmits(['press', 'author', 'more', 'product', 'like', 'comment', 'share', 'follow']);

const authorName = computed(() => props.item.authorName || props.item.author || '匿名');
const authorTag = computed(() => [props.item.city, props.item.tag].filter(Boolean).join(' · '));
const isCompany = computed(() => props.item.authorType === 'company');
const isSelf = computed(() =>
  Boolean(props.currentUserId && props.item.authorId && props.item.authorId === props.currentUserId)
);
const showFollow = computed(() => !isSelf.value);
const imageList = computed(() => {
  if (Array.isArray(props.item.images) && props.item.images.length) return props.item.images;
  return props.item.image ? [props.item.image] : [];
});
const coverImage = computed(() => (imageList.value.length ? imageList.value[0] : ''));
const imageCount = computed(() => imageList.value.length);
const liked = computed(() => Boolean((props.item as any).liked));
const textSecondary = '#4B5B53';
const accentBlue = '#2B6CB0';
const dangerColor = '#C0392B';

const emitPress = () => emit('press', props.item);
const emitAuthor = () => emit('author', props.item);
const emitMore = () => emit('more', props.item);
const emitProduct = () => emit('product', props.item);
const emitLike = () => emit('like', props.item);
const emitComment = () => emit('comment', props.item);
const emitShare = () => emit('share', props.item);
const emitFollow = () => emit('follow', props.item);
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-post {
  padding: $nm-space-lg;
  border-radius: $nm-radius-lg;
  background-color: $nm-surface;
  box-shadow: $nm-shadow-sm;
  border: 1rpx solid $nm-border;
  margin-bottom: $nm-space-lg;
}

.nm-post__header {
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
}

.nm-post__author {
  flex-direction: row;
  align-items: center;
  flex: 1;
  min-width: 0;
}

.nm-post__avatar {
  width: 72rpx;
  height: 72rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary-soft;
  margin-right: 12rpx;
}

.nm-post__author-info {
  flex: 1;
  min-width: 0;
}

.nm-post__name-row {
  flex-direction: row;
  align-items: center;
}

.nm-post__name {
  font-size: $nm-font-body;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-post__verify {
  margin-left: 6rpx;
  font-size: $nm-font-caption;
  color: $nm-accent-blue;
}

.nm-post__meta {
  margin-top: 4rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-post__intimacy {
  margin-top: 8rpx;
}

.nm-post__intimacy-text {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-post__intimacy-track {
  margin-top: 6rpx;
  height: 10rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-border;
  overflow: hidden;
}

.nm-post__intimacy-fill {
  height: 100%;
  background-color: $nm-brand-primary;
}

.nm-post__header-actions {
  flex-direction: row;
  align-items: center;
}

.nm-post__follow {
  padding: 6rpx 16rpx;
  border-radius: $nm-radius-pill;
  border: 1rpx solid $nm-brand-primary;
}

.nm-post__follow--active {
  border-color: $nm-border;
}

.nm-post__follow-text {
  font-size: $nm-font-caption;
  color: $nm-brand-primary;
}

.nm-post__follow-text--active {
  color: $nm-text-secondary;
}

.nm-post__more {
  margin-left: 12rpx;
  padding: 4rpx 8rpx;
}

.nm-post__more-icon {
  color: $nm-text-secondary;
}

.nm-post__media {
  margin-top: $nm-space-md;
  position: relative;
}

.nm-post__media-image {
  width: 100%;
  height: 320rpx;
  border-radius: $nm-radius-md;
  background-color: $nm-skeleton;
}

.nm-post__media-image--empty {
  background-color: $nm-skeleton;
}

.nm-post__image-count {
  position: absolute;
  right: 12rpx;
  top: 12rpx;
  padding: 6rpx 10rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-overlay;
}

.nm-post__image-count-text {
  font-size: $nm-font-caption;
  color: $nm-text-inverse;
}

.nm-post__product-tag {
  position: absolute;
  left: 12rpx;
  bottom: 12rpx;
  padding: 6rpx 10rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary;
}

.nm-post__product-tag-text {
  font-size: $nm-font-caption;
  color: $nm-text-inverse;
}

.nm-post__title {
  margin-top: $nm-space-sm;
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-post__content {
  margin-top: 6rpx;
  font-size: $nm-font-body;
  color: $nm-text-secondary;
}

.nm-post__tags {
  flex-direction: row;
  flex-wrap: wrap;
  margin-top: $nm-space-sm;
}

.nm-tag {
  margin-right: 8rpx;
  margin-bottom: 8rpx;
  padding: 6rpx 12rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary-soft;
}

.nm-tag__text {
  font-size: $nm-font-caption;
  color: $nm-brand-primary;
}

.nm-post__footer {
  margin-top: $nm-space-md;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
}

.nm-post__time {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-post__actions {
  flex-direction: row;
  align-items: center;
}

.nm-post__action {
  flex-direction: row;
  align-items: center;
  margin-left: 12rpx;
}

.nm-post__action-icon {
  color: $nm-text-secondary;
}

.nm-post__action-text {
  margin-left: 6rpx;
  font-size: $nm-font-caption;
  line-height: $nm-line-caption;
  color: $nm-text-secondary;
}
</style>

// 交付包/爱买买-前端源码/src/components/cards/PostCard.tsx
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Post } from '../../types';
import { useTheme } from '../../theme';
import { Tag } from '../ui';
import { PostActions, ProductTag } from '../posts';

type PostCardProps = {
  post: Post;
  liked?: boolean;
  currentUserId?: string;
  onPress?: (post: Post) => void;
  onAuthorPress?: (post: Post) => void;
  onMore?: (post: Post) => void;
  onProductPress?: (post: Post) => void;
  onLike?: (post: Post) => void;
  onComment?: (post: Post) => void;
  onShare?: (post: Post) => void;
  onFollowToggle?: (post: Post) => void;
};

// 帖子卡片：爱买买圈信息流主卡（公共组件需中文注释）
export const PostCard = ({
  post,
  liked,
  currentUserId,
  onPress,
  onAuthorPress,
  onMore,
  onProductPress,
  onLike,
  onComment,
  onShare,
  onFollowToggle,
}: PostCardProps) => {
  const { colors, radius, shadow, spacing, typography } = useTheme();
  const isCompany = post.author.type === 'company';
  const images = post.images ?? [];
  const isSelf = currentUserId ? post.author.id === currentUserId : false;
  const isFollowed = Boolean(post.author.isFollowed);
  const intimacyLevel = Math.min(100, Math.max(0, post.author.intimacyLevel ?? 0));
  const canFollow = !isSelf && typeof onFollowToggle === 'function';

  return (
    <Pressable
      onPress={() => onPress?.(post)}
      style={[styles.card, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}
    >
      <View style={styles.headerRow}>
        <Pressable onPress={() => onAuthorPress?.(post)} style={styles.authorRow} hitSlop={8}>
          {post.author.avatar ? (
            <Image source={{ uri: post.author.avatar }} style={styles.avatar} />
          ) : (
            <View style={[styles.avatar, { backgroundColor: colors.brand.primarySoft }]} />
          )}
          <View>
            <View style={styles.nameRow}>
              <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>{post.author.name}</Text>
              {isCompany && post.author.verified ? (
                <MaterialCommunityIcons name="check-decagram" size={14} color={colors.accent.blue} style={{ marginLeft: 4 }} />
              ) : null}
            </View>
            {isCompany && post.author.title ? (
              <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                {post.author.title}
              </Text>
            ) : post.author.tags?.length ? (
              <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                {post.author.tags[0]}
              </Text>
            ) : null}
            {isFollowed ? (
              <View style={styles.intimacyRow}>
                <Text style={[typography.caption, { color: colors.text.secondary }]}>亲密度 {intimacyLevel}%</Text>
                <View style={[styles.intimacyTrack, { backgroundColor: colors.border }]}>
                  <View
                    style={[styles.intimacyFill, { backgroundColor: colors.brand.primary, width: `${intimacyLevel}%` }]}
                  />
                </View>
              </View>
            ) : null}
          </View>
        </Pressable>
        <View style={styles.headerActions}>
          {canFollow ? (
            <Pressable
              onPress={(event) => {
                event.stopPropagation();
                onFollowToggle?.(post);
              }}
              style={[
                styles.followButton,
                {
                  backgroundColor: isFollowed ? colors.surface : colors.brand.primary,
                  borderColor: isFollowed ? colors.border : colors.brand.primary,
                  borderRadius: radius.pill,
                },
              ]}
            >
              <Text style={[typography.caption, { color: isFollowed ? colors.text.secondary : colors.text.inverse }]}>
                {isFollowed ? '已关注' : '关注'}
              </Text>
            </Pressable>
          ) : null}
          <Pressable onPress={() => onMore?.(post)} hitSlop={10} style={styles.moreButton}>
            <MaterialCommunityIcons name="dots-horizontal" size={18} color={colors.text.secondary} />
          </Pressable>
        </View>
      </View>

      <View style={styles.imageWrap}>
        {images[0] ? (
          <Image source={{ uri: images[0] }} style={[styles.cover, { borderRadius: radius.md }]} />
        ) : null}
        {images.length > 1 ? (
          <View style={[styles.imageCount, { backgroundColor: colors.overlay, borderRadius: radius.pill }]}>
            <Text style={[typography.caption, { color: colors.text.inverse }]}>+{images.length - 1}</Text>
          </View>
        ) : null}
        {post.productId ? (
          <ProductTag
            label={post.productTagLabel ?? '即看即买'}
            onPress={() => onProductPress?.(post)}
            style={styles.productTag}
          />
        ) : null}
      </View>

      <Text style={[typography.bodyStrong, { color: colors.text.primary, marginTop: spacing.sm }]} numberOfLines={2}>
        {post.title}
      </Text>
      <Text style={[typography.body, { color: colors.text.secondary, marginTop: spacing.xs }]} numberOfLines={3}>
        {post.content}
      </Text>

      {post.tags?.length ? (
        <View style={styles.tagRow}>
          {post.tags.map((tag, index) => (
            <Tag key={`${post.id}-${tag}-${index}`} label={tag} tone="neutral" style={{ marginRight: spacing.xs }} />
          ))}
        </View>
      ) : null}

      <View style={styles.footerRow}>
        <Text style={[typography.caption, { color: colors.text.secondary }]}>{post.createdAt}</Text>
        <PostActions
          liked={liked ?? false}
          likeCount={post.likeCount}
          commentCount={post.commentCount}
          shareCount={post.shareCount}
          onLike={() => onLike?.(post)}
          onComment={() => onComment?.(post)}
          onShare={() => onShare?.(post)}
        />
      </View>
    </Pressable>
  );
};

const styles = StyleSheet.create({
  card: {
    padding: 16,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  intimacyRow: {
    marginTop: 6,
  },
  intimacyTrack: {
    height: 4,
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 4,
    width: 140,
  },
  intimacyFill: {
    height: '100%',
    borderRadius: 999,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  moreButton: {
    padding: 4,
  },
  followButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    marginRight: 6,
  },
  imageWrap: {
    marginTop: 12,
  },
  cover: {
    width: '100%',
    height: 190,
  },
  imageCount: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  productTag: {
    position: 'absolute',
    left: 10,
    bottom: 10,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
});
