// 交付包/uniapp/src/pages-sub/me/appearance.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="头像框与装扮" />
    <scroll-view
      class="nm-page"
      scroll-y
      refresher-enabled
      :refresher-triggered="refreshing"
      @refresherrefresh="onRefresh"
    >
      <view v-if="loading" class="nm-loading">
        <Skeleton :count="2" type="card" />
      </view>
      <ErrorState v-else-if="errorMessage" :text="errorMessage" @retry="fetchProfile" />
      <view v-else-if="!profile" class="nm-loading">
        <EmptyState text="暂无资料" />
      </view>
      <view v-else>
        <view class="nm-preview">
          <view class="nm-preview__center">
            <AvatarFrame :uri="selectedAvatar || profile.avatar" :frame="selectedFrame" :size="92" />
            <text class="nm-preview__name">{{ profile.name }}</text>
            <text class="nm-preview__hint">预览头像框效果（占位）</text>
            <view v-if="selectedFrame?.expireAt" class="nm-preview__tag">
              <Tag :label="`有效期至 ${selectedFrame.expireAt}`" tone="neutral" />
            </view>
          </view>
        </view>

        <view class="nm-section">
          <text class="nm-section__title">选择头像</text>
          <view class="nm-avatar-row">
            <view
              v-for="avatar in avatarOptions"
              :key="avatar"
              :class="['nm-avatar-option', selectedAvatar === avatar ? 'nm-avatar-option--active' : '']"
              @click="selectedAvatar = avatar"
            >
              <AvatarFrame :uri="avatar" :frame="selectedAvatar === avatar ? selectedFrame : null" :size="54" />
              <text
                :class="['nm-avatar-option__text', selectedAvatar === avatar ? 'nm-avatar-option__text--active' : '']"
              >{{ selectedAvatar === avatar ? '已选' : '选择' }}</text>
            </view>
          </view>
          <text class="nm-section__hint">当前为前端占位头像库，后续可接入上传/拍照能力</text>
        </view>

        <view class="nm-section">
          <text class="nm-section__title">选择头像框</text>
          <view class="nm-frame-list">
            <view
              v-for="option in frameOptions"
              :key="option.id"
              :class="['nm-frame-row', selectedFrameId === option.id ? 'nm-frame-row--active' : '']"
              @click="selectedFrameId = option.id"
            >
              <AvatarFrame :uri="profile.avatar" :frame="option.frame" :size="56" />
              <view class="nm-frame-info">
                <text class="nm-frame-title">{{ option.label }}</text>
                <text class="nm-frame-hint">{{ option.hint }}</text>
              </view>
              <Tag v-if="selectedFrameId === option.id" label="已选" tone="brand" />
              <text v-else class="nm-frame-select">选择</text>
            </view>
          </view>
        </view>

        <view class="nm-primary" @click="saveAppearance">保存（占位）</view>
      </view>
    </scroll-view>
  </Screen>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { Screen, AppHeader, Skeleton, ErrorState, EmptyState, AvatarFrame, Tag } from '@/components';
import { UserRepo, type UserProfile } from '@/services/repos';

const loading = ref(true);
const refreshing = ref(false);
const errorMessage = ref('');
const profile = ref<UserProfile | null>(null);

type FrameOption = {
  id: string;
  label: string;
  frame: { id: string; type: 'vip' | 'task' | 'limited'; expireAt?: string } | null;
  hint: string;
};

const frameOptions: FrameOption[] = [
  { id: 'default', label: '默认', frame: null, hint: '所有用户可用' },
  { id: 'vip', label: 'VIP 动态框', frame: { id: 'frame-vip', type: 'vip' }, hint: '会员专属（占位）' },
  { id: 'task', label: '任务奖励框', frame: { id: 'frame-task', type: 'task', expireAt: '2026-12-31' }, hint: '完成任务解锁（占位）' },
  { id: 'limited', label: '限时框', frame: { id: 'frame-limited', type: 'limited', expireAt: '2026-06-30' }, hint: '限时活动/福利（占位）' },
];

const avatarOptions = [
  'https://placehold.co/200x200/png?text=Farm',
  'https://placehold.co/200x200/png?text=Leaf',
  'https://placehold.co/200x200/png?text=AI',
  'https://placehold.co/200x200/png?text=Grow',
];

const selectedFrameId = ref('default');
const selectedAvatar = ref<string | null>(null);

const selectedFrame = computed(() => {
  const option = frameOptions.find((item) => item.id === selectedFrameId.value);
  return option ? option.frame : null;
});

const fetchProfile = async () => {
  loading.value = true;
  const res = await UserRepo.profile();
  if (res.ok) {
    errorMessage.value = '';
    profile.value = res.data;
    selectedAvatar.value = res.data.avatar || null;
  } else {
    errorMessage.value = res.error.message || '加载失败';
  }
  loading.value = false;
};

const onRefresh = async () => {
  if (refreshing.value) return;
  refreshing.value = true;
  await fetchProfile();
  refreshing.value = false;
};

const saveAppearance = async () => {
  if (!profile.value) return;
  const res = await UserRepo.updateProfile({
    avatar: selectedAvatar.value || profile.value.avatar,
    avatarFrame: selectedFrame.value || undefined,
  });
  if (res.ok) {
    uni.showToast({ title: '头像设置已保存', icon: 'success' });
  } else {
    uni.showToast({ title: res.error.message || '保存失败', icon: 'none' });
  }
};

fetchProfile();
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-loading {
  padding: $nm-space-xl 0;
}

.nm-preview {
  padding: 36rpx;
  border-radius: $nm-radius-lg;
  background-color: $nm-surface;
  box-shadow: $nm-shadow-sm;
  border: 1rpx solid transparent;
}

.nm-preview__center {
  align-items: center;
}

.nm-preview__name {
  margin-top: 20rpx;
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-preview__hint {
  margin-top: 8rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-preview__tag {
  margin-top: 20rpx;
}

.nm-section {
  margin-top: $nm-space-lg;
}

.nm-section__title {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-section__hint {
  margin-top: 12rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-avatar-row {
  margin-top: 20rpx;
  flex-direction: row;
  flex-wrap: wrap;
}

.nm-avatar-option {
  padding: 20rpx;
  margin-right: 20rpx;
  margin-bottom: 20rpx;
  border-radius: $nm-radius-lg;
  border: 1rpx solid $nm-border;
  background-color: $nm-surface;
  align-items: center;
}

.nm-avatar-option--active {
  border-color: $nm-brand-primary;
}

.nm-avatar-option__text {
  margin-top: 12rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-avatar-option__text--active {
  color: $nm-brand-primary;
}

.nm-frame-list {
  margin-top: $nm-space-sm;
}

.nm-frame-row {
  padding: 28rpx;
  border-radius: $nm-radius-lg;
  border: 1rpx solid $nm-border;
  background-color: $nm-surface;
  box-shadow: $nm-shadow-sm;
  flex-direction: row;
  align-items: center;
  margin-bottom: 24rpx;
}

.nm-frame-row--active {
  border-color: $nm-brand-primary;
}

.nm-frame-info {
  flex: 1;
  margin-left: $nm-space-sm;
}

.nm-frame-title {
  font-size: $nm-font-body;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-frame-hint {
  margin-top: 8rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-primary {
  margin-top: $nm-space-lg;
  padding: 24rpx 0;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary;
  text-align: center;
  color: $nm-text-inverse;
  font-weight: 600;
}

.nm-frame-select {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}
</style>

// 交付包/爱买买-前端源码/app/me/appearance.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AppHeader, Screen } from '../../src/components/layout';
import { EmptyState, ErrorState, Skeleton, useToast } from '../../src/components/feedback';
import { AvatarFrame, Tag } from '../../src/components/ui';
import { UserRepo } from '../../src/repos';
import { useTheme } from '../../src/theme';
import { AvatarFrame as AvatarFrameType } from '../../src/types';

type FrameOption = {
  id: string;
  label: string;
  frame: AvatarFrameType | null;
  hint: string;
};

export default function MeAppearanceScreen() {
  const { colors, radius, shadow, spacing, typography } = useTheme();
  const { show } = useToast();
  const queryClient = useQueryClient();
  const [refreshing, setRefreshing] = useState(false);
  const [selectedFrameId, setSelectedFrameId] = useState<string>('default');
  const [selectedAvatar, setSelectedAvatar] = useState<string | null>(null);

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['me-appearance-profile'],
    queryFn: () => UserRepo.profile(),
  });

  const profile = data?.ok ? data.data : null;
  const error = data && !data.ok ? data.error : null;

  const options = useMemo<FrameOption[]>(
    () => [
      { id: 'default', label: '默认', frame: null, hint: '所有用户可用' },
      {
        id: 'vip',
        label: 'VIP 动态框',
        frame: { id: 'frame-vip', type: 'vip', label: 'VIP', expiresAt: undefined },
        hint: '会员专属（占位）',
      },
      {
        id: 'task',
        label: '任务奖励框',
        frame: { id: 'frame-task', type: 'task', label: '任务', expiresAt: '2026-12-31' },
        hint: '完成任务解锁（占位）',
      },
      {
        id: 'limited',
        label: '限时框',
        frame: { id: 'frame-limited', type: 'limited', label: '限时', expiresAt: '2026-06-30' },
        hint: '限时活动/福利（占位）',
      },
    ],
    []
  );
  const avatarOptions = useMemo(
    () => [
      'https://placehold.co/200x200/png?text=Farm',
      'https://placehold.co/200x200/png?text=Leaf',
      'https://placehold.co/200x200/png?text=AI',
      'https://placehold.co/200x200/png?text=Grow',
    ],
    []
  );

  const handleRefresh = async () => {
    setRefreshing(true);
    await refetch();
    setRefreshing(false);
  };

  useEffect(() => {
    if (!profile) {
      return;
    }
    setSelectedAvatar(profile.avatar);
  }, [profile]);

  const selectedOption = options.find((option) => option.id === selectedFrameId) ?? options[0];

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="头像框与装扮" />
      {isLoading ? (
        <View style={{ padding: spacing.xl }}>
          <Skeleton height={160} radius={radius.lg} />
          <View style={{ height: spacing.md }} />
          <Skeleton height={220} radius={radius.lg} />
        </View>
      ) : error ? (
        <View style={{ padding: spacing.xl }}>
          <ErrorState title="加载失败" description={error.displayMessage ?? '请稍后重试'} onAction={refetch} />
        </View>
      ) : !profile ? (
        <View style={{ padding: spacing.xl }}>
          <EmptyState title="暂无资料" description="请稍后再试" />
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
        >
          <View style={[styles.previewCard, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}>
            <View style={{ alignItems: 'center' }}>
              <AvatarFrame uri={selectedAvatar ?? profile.avatar} size={92} frame={selectedOption.frame} />
              <Text style={[typography.title3, { color: colors.text.primary, marginTop: 10 }]}>{profile.name}</Text>
              <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 4 }]}>
                预览头像框效果（占位）
              </Text>
              {selectedOption.frame?.expiresAt ? (
                <Tag label={`有效期至 ${selectedOption.frame.expiresAt}`} tone="neutral" style={{ marginTop: 10 }} />
              ) : null}
            </View>
          </View>

          <View style={{ marginTop: spacing.lg }}>
            <Text style={[typography.title3, { color: colors.text.primary }]}>选择头像</Text>
            <View style={styles.avatarRow}>
              {avatarOptions.map((avatar) => {
                const active = avatar === selectedAvatar;
                return (
                  <Pressable
                    key={avatar}
                    onPress={() => setSelectedAvatar(avatar)}
                    style={[
                      styles.avatarOption,
                      {
                        borderColor: active ? colors.brand.primary : colors.border,
                        backgroundColor: colors.surface,
                        borderRadius: radius.lg,
                      },
                    ]}
                  >
                    <AvatarFrame uri={avatar} size={54} frame={active ? selectedOption.frame : null} />
                    <Text style={[typography.caption, { color: active ? colors.brand.primary : colors.text.secondary, marginTop: 6 }]}>
                      {active ? '已选' : '选择'}
                    </Text>
                  </Pressable>
                );
              })}
            </View>
            <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 6 }]}>
              当前为前端占位头像库，后续可接入上传/拍照能力
            </Text>
          </View>

          <View style={{ marginTop: spacing.lg }}>
            <Text style={[typography.title3, { color: colors.text.primary }]}>选择头像框</Text>
            <View style={{ marginTop: spacing.sm }}>
              {options.map((option) => {
                const active = option.id === selectedFrameId;
                return (
                  <Pressable
                    key={option.id}
                    onPress={() => setSelectedFrameId(option.id)}
                    style={[
                      styles.optionRow,
                      shadow.sm,
                      {
                        backgroundColor: colors.surface,
                        borderRadius: radius.lg,
                        borderColor: active ? colors.brand.primary : 'transparent',
                      },
                    ]}
                  >
                    <AvatarFrame uri={profile.avatar} size={56} frame={option.frame} />
                    <View style={{ flex: 1, marginLeft: 12 }}>
                      <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>{option.label}</Text>
                      <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 4 }]}>{option.hint}</Text>
                    </View>
                    {active ? (
                      <Tag label="已选" tone="brand" />
                    ) : (
                      <Text style={[typography.caption, { color: colors.text.secondary }]}>选择</Text>
                    )}
                  </Pressable>
                );
              })}
            </View>
          </View>

          <Pressable
            onPress={async () => {
              // 保存头像与头像框占位（复杂业务逻辑需中文注释）
              const result = await UserRepo.updateProfile({
                avatar: selectedAvatar ?? profile.avatar,
                avatarFrame: selectedOption.frame ?? undefined,
              });
              if (!result.ok) {
                show({ message: result.error.displayMessage ?? '保存失败', type: 'error' });
                return;
              }
              await Promise.all([
                queryClient.invalidateQueries({ queryKey: ['me-profile'] }),
                queryClient.invalidateQueries({ queryKey: ['me-profile-detail'] }),
                queryClient.invalidateQueries({ queryKey: ['me-appearance-profile'] }),
              ]);
              show({ message: '头像设置已保存', type: 'success' });
            }}
            style={[styles.saveButton, { backgroundColor: colors.brand.primary, borderRadius: radius.pill }]}
          >
            <Text style={[typography.bodyStrong, { color: colors.text.inverse }]}>保存（占位）</Text>
          </Pressable>
        </ScrollView>
      )}
    </Screen>
  );
}

const styles = StyleSheet.create({
  previewCard: {
    padding: 18,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  avatarRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  avatarOption: {
    borderWidth: 1,
    padding: 10,
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 10,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderWidth: 1,
    marginBottom: 12,
  },
  saveButton: {
    marginTop: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
});
