// 交付包/uniapp/src/pages-sub/me/recommend.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="为你推荐" />
    <scroll-view
      class="nm-page"
      scroll-y
      refresher-enabled
      :refresher-triggered="refreshing"
      @refresherrefresh="onRefresh"
    >
      <EmptyState text="推荐列表待接入" hint="后续展示完整个性推荐列表" />
    </scroll-view>
  </Screen>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { Screen, AppHeader, EmptyState } from '@/components';

const refreshing = ref(false);

const onRefresh = async () => {
  if (refreshing.value) return;
  refreshing.value = true;
  setTimeout(() => {
    refreshing.value = false;
  }, 300);
};
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}
</style>

// 交付包/爱买买-前端源码/app/me/recommend.tsx
import React, { useState } from 'react';
import { RefreshControl, ScrollView, View } from 'react-native';
import { AppHeader, Screen } from '../../src/components/layout';
import { EmptyState } from '../../src/components/feedback';
import { useTheme } from '../../src/theme';

export default function RecommendScreen() {
  const { spacing } = useTheme();
  const [refreshing, setRefreshing] = useState(false);
  const handleRefresh = async () => {
    setRefreshing(true);
    await new Promise((resolve) => setTimeout(resolve, 300));
    setRefreshing(false);
  };

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="为你推荐" />
      <ScrollView
        contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
      >
        <EmptyState title="推荐列表待接入" description="后续展示完整个性推荐列表" />
      </ScrollView>
    </Screen>
  );
}
