// 交付包/uniapp/src/components/ui/Tag.vue
<template>
  <view :class="['nm-tag', toneClass]">
    <text class="nm-tag__text">{{ label }}</text>
  </view>
</template>

<script setup lang="ts">
// 标签组件：展示轻量标签（公共组件需中文注释）
const props = withDefaults(
  defineProps<{
    label: string;
    tone?: 'neutral' | 'accent' | 'success' | 'brand';
  }>(),
  {
    tone: 'neutral',
  }
);

const toneClass = `nm-tag--${props.tone}`;
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-tag {
  padding: 8rpx 16rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-border;
}

.nm-tag__text {
  font-size: $nm-font-caption;
  line-height: $nm-line-caption;
  color: $nm-text-secondary;
}

.nm-tag--accent {
  background-color: $nm-accent-blue-soft;
  border-color: transparent;
}

.nm-tag--accent .nm-tag__text {
  color: $nm-accent-blue;
}

.nm-tag--success {
  background-color: $nm-brand-primary-soft;
  border-color: transparent;
}

.nm-tag--success .nm-tag__text {
  color: $nm-brand-primary;
}

.nm-tag--brand {
  background-color: $nm-brand-primary-soft;
  border-color: transparent;
}

.nm-tag--brand .nm-tag__text {
  color: $nm-brand-primary;
}
</style>

// 交付包/爱买买-前端源码/src/components/ui/Tag.tsx
import React from 'react';
import { StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { useTheme } from '../../theme';

type TagProps = {
  label: string;
  tone?: 'brand' | 'accent' | 'neutral';
  style?: StyleProp<ViewStyle>;
};

// 标签组件：用于展示可信/品类等轻量信息
export const Tag = ({ label, tone = 'brand', style }: TagProps) => {
  const { colors, radius, spacing, typography } = useTheme();

  const toneStyle = {
    brand: { backgroundColor: colors.brand.primarySoft, color: colors.brand.primary },
    accent: { backgroundColor: colors.accent.blueSoft, color: colors.accent.blue },
    neutral: { backgroundColor: colors.border, color: colors.text.secondary },
  }[tone];

  return (
    <View style={[styles.tag, { borderRadius: radius.pill, paddingHorizontal: spacing.sm }, style, { backgroundColor: toneStyle.backgroundColor }]}>
      <Text style={[typography.caption, { color: toneStyle.color }]}>{label}</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  tag: {
    paddingVertical: 4,
  },
});
