// 交付包/uniapp/src/pages-sub/circle/moderation.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="举报与审核" />
    <scroll-view
      class="nm-page"
      scroll-y
      refresher-enabled
      :refresher-triggered="refreshing"
      @refresherrefresh="onRefresh"
    >
      <text class="nm-note">审核队列（占位）</text>

      <view v-if="loading" class="nm-state">
        <Skeleton :count="2" type="card" />
      </view>
      <view v-else-if="errorMessage" class="nm-state">
        <ErrorState :text="errorMessage" @retry="onRefresh" />
      </view>
      <view v-else-if="items.length === 0" class="nm-state">
        <EmptyState text="暂无举报" hint="待审核内容会出现在这里" />
      </view>
      <view v-else>
        <view
          v-for="item in items"
          :key="item.postId"
          class="nm-row"
          @click="openPost(item.postId)"
        >
          <view class="nm-info">
            <text class="nm-title" number-of-lines="1">{{ item.title }}</text>
            <text class="nm-meta">{{ item.authorName }} · 举报 {{ item.reportCount }} 条</text>
            <text v-if="item.lastReviewedAt" class="nm-meta">最近审核：{{ item.lastReviewedAt }}</text>
          </view>
          <view :class="['nm-pill', toneClass(item.status)]">
            <text class="nm-pill__text">{{ moderationLabel(item.status) }}</text>
          </view>
        </view>
      </view>
    </scroll-view>
  </Screen>
</template>

<script setup lang="ts">
import { navTo } from '@/utils/nav';
import { onMounted, ref } from 'vue';
import { Screen, AppHeader, EmptyState, ErrorState, Skeleton } from '@/components';
import { ContentOpsRepo, type ModerationQueueItem, type ModerationStatus } from '@/services/repos';

const items = ref<ModerationQueueItem[]>([]);
const loading = ref(false);
const refreshing = ref(false);
const errorMessage = ref('');

const fetchQueue = async () => {
  loading.value = true;
  const res = await ContentOpsRepo.listModerationQueue();
  if (res.ok) {
    items.value = res.data;
    errorMessage.value = '';
  } else {
    errorMessage.value = res.error.message || '加载失败';
  }
  loading.value = false;
  refreshing.value = false;
};

const onRefresh = () => {
  if (refreshing.value) return;
  refreshing.value = true;
  fetchQueue();
};

const openPost = (postId: string) => {
  navTo({ url: `/pages-sub/circle/post-detail?id=${postId}` });
};

const toneClass = (status: ModerationStatus) => {
  if (status === 'flagged') return 'nm-pill--accent';
  if (status === 'approved') return 'nm-pill--brand';
  return 'nm-pill--neutral';
};

const moderationLabel = (status: ModerationStatus) => ContentOpsRepo.getModerationLabel(status);

onMounted(() => {
  fetchQueue();
});
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-note {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
  margin-bottom: 0;
}

.nm-row {
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
  padding: $nm-space-md 0;
  border-bottom: 1rpx solid $nm-border;
}

.nm-info {
  flex: 1;
  margin-right: 24rpx;
}

.nm-title {
  font-size: $nm-font-body;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-meta {
  margin-top: 4rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-pill {
  padding: 8rpx 20rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-border;
}

.nm-pill__text {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-pill--brand {
  background-color: $nm-brand-primary-soft;
}

.nm-pill--brand .nm-pill__text {
  color: $nm-brand-primary;
}

.nm-pill--accent {
  background-color: $nm-accent-blue-soft;
}

.nm-pill--accent .nm-pill__text {
  color: $nm-accent-blue;
}

.nm-pill--neutral {
  background-color: $nm-border;
}

.nm-pill--neutral .nm-pill__text {
  color: $nm-text-secondary;
}

.nm-state {
  margin-top: $nm-space-md;
}
</style>

// 交付包/爱买买-前端源码/app/circle/moderation.tsx
import React, { useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { AppHeader, Screen } from '../../src/components/layout';
import { EmptyState, ErrorState, Skeleton } from '../../src/components/feedback';
import { ContentOpsRepo } from '../../src/repos';
import { StatusPill } from '../../src/components/ui';
import { useTheme } from '../../src/theme';
import { AppError } from '../../src/types';

export default function CircleModerationScreen() {
  const { colors, radius, spacing, typography } = useTheme();
  const router = useRouter();
  const [refreshing, setRefreshing] = useState(false);

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['circle-moderation'],
    queryFn: () => ContentOpsRepo.listModerationQueue(),
  });
  const handleRefresh = async () => {
    setRefreshing(true);
    await refetch();
    setRefreshing(false);
  };

  const listError = data && !data.ok ? data.error : null;
  const items = data?.ok ? data.data : [];

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="举报与审核" />
      <ScrollView
        contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
      >
        <Text style={[typography.caption, { color: colors.text.secondary }]}>审核队列（占位）</Text>
        {isLoading ? (
          <View style={{ marginTop: spacing.md }}>
            <Skeleton height={120} radius={radius.lg} />
            <View style={{ height: spacing.md }} />
            <Skeleton height={120} radius={radius.lg} />
          </View>
        ) : (listError as AppError | null) ? (
          <View style={{ marginTop: spacing.md }}>
            <ErrorState
              title="加载失败"
              description={listError?.displayMessage ?? '请稍后再试'}
              onAction={refetch}
            />
          </View>
        ) : items.length === 0 ? (
          <View style={{ marginTop: spacing.md }}>
            <EmptyState title="暂无举报" description="待审核内容会出现在这里" />
          </View>
        ) : (
          items.map((item) => {
            const tone = item.status === 'flagged' ? 'accent' : item.status === 'approved' ? 'brand' : 'neutral';
            return (
              <Pressable
                key={item.postId}
                onPress={() => router.push({ pathname: '/post/[id]', params: { id: item.postId } })}
                style={[styles.queueRow, { borderBottomColor: colors.border }]}
              >
                <View style={styles.queueInfo}>
                  <Text style={[typography.bodyStrong, { color: colors.text.primary }]} numberOfLines={1}>
                    {item.title}
                  </Text>
                  <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                    {item.authorName} · 举报 {item.reportCount} 条
                  </Text>
                  {item.lastReviewedAt ? (
                    <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                      最近审核：{item.lastReviewedAt}
                    </Text>
                  ) : null}
                </View>
                <StatusPill
                  label={ContentOpsRepo.getModerationLabel(item.status)}
                  tone={tone as 'brand' | 'accent' | 'neutral'}
                />
              </Pressable>
            );
          })
        )}
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  queueRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  queueInfo: {
    flex: 1,
    marginRight: 12,
  },
});
