// 交付包/uniapp/src/pages-sub/circle/ops.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="运营中心" />
    <scroll-view
      class="nm-page"
      scroll-y
      refresher-enabled
      :refresher-triggered="refreshing"
      @refresherrefresh="onRefresh"
    >
      <text class="nm-section-title">数据与运营</text>
      <view class="nm-section">
        <view class="nm-card" @click="goAnalytics">
          <view class="nm-card__row">
            <Icon class="nm-card__icon" name="chart-box-outline" :size="40" :color="brandPrimary" />
            <view class="nm-card__info">
              <text class="nm-card__title">企业内容分析面板</text>
              <text class="nm-card__desc">内容表现、互动结构、趋势概览</text>
            </view>
          </view>
        </view>
        <view class="nm-card" @click="goInterests">
          <view class="nm-card__row">
            <Icon class="nm-card__icon" name="brain" :size="40" :color="accentBlue" />
            <view class="nm-card__info">
              <text class="nm-card__title">用户兴趣图谱</text>
              <text class="nm-card__desc">兴趣标签、行为信号、推荐依据</text>
            </view>
          </view>
        </view>
      </view>

      <text class="nm-section-title nm-section-title--spaced">风控与精华</text>
      <view class="nm-section">
        <view class="nm-card" @click="goFeatured">
          <view class="nm-card__row">
            <Icon class="nm-card__icon" name="star-four-points" :size="40" :color="accentBlue" />
            <view class="nm-card__info">
              <text class="nm-card__title">精华专区</text>
              <text class="nm-card__desc">精选内容集合，提升曝光</text>
            </view>
          </view>
        </view>
        <view class="nm-card" @click="goRankings">
          <view class="nm-card__row">
            <Icon class="nm-card__icon" name="trophy-outline" :size="40" :color="brandPrimary" />
            <view class="nm-card__info">
              <text class="nm-card__title">榜单与贡献值</text>
              <text class="nm-card__desc">创作者排行与贡献值激励</text>
            </view>
          </view>
        </view>
        <view class="nm-card" @click="goModeration">
          <view class="nm-card__row">
            <Icon class="nm-card__icon" name="shield-check-outline" :size="40" :color="accentBlue" />
            <view class="nm-card__info">
              <text class="nm-card__title">举报与审核</text>
              <text class="nm-card__desc">举报记录与审核状态追踪</text>
            </view>
          </view>
        </view>
      </view>
    </scroll-view>
  </Screen>
</template>

<script setup lang="ts">
import { navTo } from '@/utils/nav';
import { ref } from 'vue';
import { Screen, AppHeader, Icon } from '@/components';

const brandPrimary = '#2F8F4E';
const accentBlue = '#2B6CB0';
const refreshing = ref(false);

const onRefresh = () => {
  if (refreshing.value) return;
  refreshing.value = true;
  setTimeout(() => {
    refreshing.value = false;
  }, 300);
};

const goAnalytics = () => navTo({ url: '/pages-sub/circle/analytics' });
const goInterests = () => navTo({ url: '/pages-sub/circle/interests' });
const goFeatured = () => navTo({ url: '/pages-sub/circle/featured' });
const goRankings = () => navTo({ url: '/pages-sub/circle/rankings' });
const goModeration = () => navTo({ url: '/pages-sub/circle/moderation' });
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-section {
  margin-top: $nm-space-sm;
}

.nm-section-title {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-section-title--spaced {
  margin-top: $nm-space-xl;
}

.nm-card {
  padding: 28rpx;
  border-radius: $nm-radius-lg;
  background-color: $nm-surface;
  box-shadow: $nm-shadow-sm;
  border: 1rpx solid transparent;
  margin-bottom: $nm-space-md;
}

.nm-card__row {
  flex-direction: row;
  align-items: center;
}

.nm-card__icon {
}

.nm-card__info {
  margin-left: $nm-space-sm;
}

.nm-card__title {
  font-size: $nm-font-body;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-card__desc {
  margin-top: 4rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}
</style>

// 交付包/爱买买-前端源码/app/circle/ops.tsx
import React, { useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { AppHeader, Screen } from '../../src/components/layout';
import { useTheme } from '../../src/theme';

export default function CircleOpsScreen() {
  const { colors, radius, shadow, spacing, typography } = useTheme();
  const router = useRouter();
  const [refreshing, setRefreshing] = useState(false);
  const handleRefresh = async () => {
    setRefreshing(true);
    await new Promise((resolve) => setTimeout(resolve, 300));
    setRefreshing(false);
  };

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="运营中心" />
      <ScrollView
        contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
      >
        <Text style={[typography.title3, { color: colors.text.primary }]}>数据与运营</Text>
        <View style={{ marginTop: spacing.sm }}>
          <Pressable
            onPress={() => router.push('/circle/analytics')}
            style={[styles.card, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}
          >
            <View style={styles.cardRow}>
              <MaterialCommunityIcons name="chart-box-outline" size={20} color={colors.brand.primary} />
              <View style={{ marginLeft: spacing.sm }}>
                <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>企业内容分析面板</Text>
                <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                  内容表现、互动结构、趋势概览
                </Text>
              </View>
            </View>
          </Pressable>
          <Pressable
            onPress={() => router.push('/circle/interests')}
            style={[styles.card, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}
          >
            <View style={styles.cardRow}>
              <MaterialCommunityIcons name="brain" size={20} color={colors.accent.blue} />
              <View style={{ marginLeft: spacing.sm }}>
                <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>用户兴趣图谱</Text>
                <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                  兴趣标签、行为信号、推荐依据
                </Text>
              </View>
            </View>
          </Pressable>
        </View>

        <Text style={[typography.title3, { color: colors.text.primary, marginTop: spacing.xl }]}>风控与精华</Text>
        <View style={{ marginTop: spacing.sm }}>
          <Pressable
            onPress={() => router.push('/circle/featured')}
            style={[styles.card, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}
          >
            <View style={styles.cardRow}>
              <MaterialCommunityIcons name="star-four-points" size={20} color={colors.accent.blue} />
              <View style={{ marginLeft: spacing.sm }}>
                <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>精华专区</Text>
                <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                  精选内容集合，提升曝光
                </Text>
              </View>
            </View>
          </Pressable>
          <Pressable
            onPress={() => router.push('/circle/rankings')}
            style={[styles.card, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}
          >
            <View style={styles.cardRow}>
              <MaterialCommunityIcons name="trophy-outline" size={20} color={colors.brand.primary} />
              <View style={{ marginLeft: spacing.sm }}>
                <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>榜单与贡献值</Text>
                <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                  创作者排行与贡献值激励
                </Text>
              </View>
            </View>
          </Pressable>
          <Pressable
            onPress={() => router.push('/circle/moderation')}
            style={[styles.card, shadow.sm, { backgroundColor: colors.surface, borderRadius: radius.lg }]}
          >
            <View style={styles.cardRow}>
              <MaterialCommunityIcons name="shield-check-outline" size={20} color={colors.accent.blue} />
              <View style={{ marginLeft: spacing.sm }}>
                <Text style={[typography.bodyStrong, { color: colors.text.primary }]}>举报与审核</Text>
                <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 2 }]}>
                  举报记录与审核状态追踪
                </Text>
              </View>
            </View>
          </Pressable>
        </View>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  card: {
    padding: 14,
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 12,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});
