// 交付包/爱买买-前端源码/src/components/posts/ProductQuickSheet.tsx
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { useQuery } from '@tanstack/react-query';
import { AppBottomSheet } from '../overlay';
import { ErrorState, Skeleton, useToast } from '../feedback';
import { ProductRepo } from '../../repos';
import { useCartStore } from '../../store';
import { useTheme } from '../../theme';
import { Price } from '../ui';

type ProductQuickSheetProps = {
  open: boolean;
  productId?: string;
  onClose: () => void;
};

// 商品快购抽屉：帖子挂商品的快捷购买入口（公共组件需中文注释）
export const ProductQuickSheet = ({ open, productId, onClose }: ProductQuickSheetProps) => {
  const { colors, radius, spacing, typography } = useTheme();
  const { show } = useToast();
  const addItem = useCartStore((state) => state.addItem);

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['product', productId],
    queryFn: () => ProductRepo.getById(String(productId)),
    enabled: Boolean(productId) && open,
  });

  return (
    <AppBottomSheet open={open} onClose={onClose} mode="auto" title="挂载商品">
      {isLoading ? (
        <View>
          <Skeleton height={120} radius={radius.lg} />
          <Skeleton height={16} radius={radius.md} style={{ marginTop: spacing.md }} />
        </View>
      ) : !data || !data.ok ? (
        <ErrorState
          title="商品加载失败"
          description={data?.ok === false ? data.error.displayMessage ?? '请稍后再试' : '请稍后再试'}
          onAction={refetch}
        />
      ) : (
        <View>
          <View style={styles.productRow}>
            <Image source={{ uri: data.data.image }} style={{ width: 84, height: 84, borderRadius: radius.md }} />
            <View style={{ flex: 1, marginLeft: spacing.md }}>
              <Text style={[typography.bodyStrong, { color: colors.text.primary }]} numberOfLines={2}>
                {data.data.title}
              </Text>
              <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 4 }]}>
                {data.data.origin}
              </Text>
              <View style={{ marginTop: 8 }}>
                <Price value={data.data.price} unit={data.data.unit} strikeValue={data.data.strikePrice} />
              </View>
            </View>
          </View>
          <Pressable
            onPress={() => {
              addItem(data.data);
              show({ message: '已加入购物车', type: 'success' });
              onClose();
            }}
            style={[styles.primaryButton, { backgroundColor: colors.brand.primary, borderRadius: radius.md }]}
          >
            <Text style={[typography.bodyStrong, { color: colors.text.inverse }]}>一键加购</Text>
          </Pressable>
        </View>
      )}
    </AppBottomSheet>
  );
};

const styles = StyleSheet.create({
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  primaryButton: {
    marginTop: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
});

// 交付包/uniapp/src/components/overlay/ProductQuickSheet.vue
<template>
  <BottomSheet :open="open" mode="auto" title="挂载商品" @close="emit('close')">
    <view class="nm-sheet">
      <Skeleton v-if="loading" :count="1" type="card" />
      <ErrorState v-else-if="errorMessage" :text="errorMessage" @retry="loadProduct" />
      <view v-else-if="product" class="nm-card">
        <image :src="product.image" class="nm-card__image" mode="aspectFill" />
        <view class="nm-card__body">
          <text class="nm-card__title">{{ product.title }}</text>
          <text class="nm-card__origin">{{ product.origin }}</text>
          <view class="nm-card__price-row">
            <text class="nm-card__price">¥{{ product.price }}</text>
            <text class="nm-card__unit">/{{ product.unit }}</text>
            <text v-if="product.strikePrice" class="nm-card__strike">¥{{ product.strikePrice }}</text>
          </view>
        </view>
      </view>
      <view v-else class="nm-empty">暂无关联商品</view>

      <view class="nm-actions">
        <view class="nm-btn nm-btn--primary" @click="addToCart">一键加购</view>
      </view>
    </view>
  </BottomSheet>
</template>

<script setup lang="ts">
// 商品快捷弹层（复刻 Expo 的 ProductQuickSheet）
import { ref, watch } from 'vue';
import { BottomSheet } from '@/components';
import { ProductRepo } from '@/services/repos';
import { CartState } from '@/services/state';
import { ErrorState, Skeleton } from '@/components';

const props = withDefaults(
  defineProps<{
    open: boolean;
    productId?: string;
  }>(),
  {
    open: false,
  }
);

const emit = defineEmits(['close']);
const product = ref<any | null>(null);
const loading = ref(false);
const errorMessage = ref('');

const loadProduct = async () => {
  if (!props.productId) {
    product.value = null;
    errorMessage.value = '';
    return;
  }
  loading.value = true;
  const res = await ProductRepo.getById(props.productId);
  if (res.ok) {
    product.value = res.data;
    errorMessage.value = '';
  } else {
    product.value = null;
    errorMessage.value = res.error.message || '商品加载失败';
  }
  loading.value = false;
};

watch(
  () => [props.open, props.productId],
  ([open]) => {
    if (open) loadProduct();
  }
);

const addToCart = () => {
  if (!product.value) return;
  // TODO(后端)：接入购物车接口后，这里应调用 CartRepo.addItem
  CartState.addProduct(
    { id: product.value.id, title: product.value.title, price: product.value.price, image: product.value.image },
    1
  );
  uni.showToast({ title: '已加入购物车', icon: 'success' });
  emit('close');
};
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-sheet {
  padding-bottom: $nm-space-xl;
}

.nm-card {
  border-radius: $nm-radius-lg;
  border: 1rpx solid $nm-border;
  background-color: $nm-surface;
  overflow: hidden;
  flex-direction: row;
  align-items: center;
  padding: $nm-space-md;
}

.nm-card__image {
  width: 168rpx;
  height: 168rpx;
  background-color: $nm-skeleton;
  border-radius: $nm-radius-md;
}

.nm-card__body {
  padding-left: $nm-space-md;
  flex: 1;
}

.nm-card__title {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-card__origin {
  margin-top: 6rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-card__price-row {
  margin-top: $nm-space-sm;
  flex-direction: row;
  align-items: baseline;
}

.nm-card__price {
  font-size: $nm-font-title3;
  font-weight: 600;
  color: $nm-brand-primary;
}

.nm-card__unit {
  margin-left: 6rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-card__strike {
  margin-left: 10rpx;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
  text-decoration: line-through;
}

.nm-empty {
  padding: $nm-space-lg;
  border-radius: $nm-radius-lg;
  border: 1rpx solid $nm-border;
  color: $nm-text-secondary;
  text-align: center;
  background-color: $nm-surface;
}

.nm-actions {
  margin-top: $nm-space-md;
  flex-direction: row;
}

.nm-btn {
  flex: 1;
  padding: 14rpx 0;
  border-radius: $nm-radius-pill;
  text-align: center;
  font-size: $nm-font-caption;
}

.nm-btn--primary {
  background-color: $nm-brand-primary;
  color: $nm-text-inverse;
}
</style>
