// 交付包/爱买买-前端源码/app/ai/chat.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  KeyboardAvoidingView,
  Platform,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { AppHeader, Screen } from '../../src/components/layout';
import { AiAssistantRepo } from '../../src/repos';
import { useTheme } from '../../src/theme';
import { AiChatMessage } from '../../src/types';
import { useToast } from '../../src/components/feedback';

export default function AiChatScreen() {
  const { colors, radius, spacing, typography } = useTheme();
  const { show } = useToast();
  const { prompt } = useLocalSearchParams<{ prompt?: string }>();
  const scrollRef = useRef<ScrollView>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [messages, setMessages] = useState<AiChatMessage[]>([]);

  const { data: shortcutData, refetch } = useQuery({
    queryKey: ['ai-shortcuts'],
    queryFn: () => AiAssistantRepo.listShortcuts(),
  });

  const shortcuts = shortcutData?.ok ? shortcutData.data : [];

  const greeting = useMemo<AiChatMessage>(
    () => ({
      id: 'ai-greeting',
      role: 'assistant',
      content: '你好，我是 AI 农管家。',
      createdAt: new Date().toISOString(),
    }),
    []
  );

  useEffect(() => {
    setMessages([greeting]);
  }, [greeting]);

  useEffect(() => {
    if (!prompt) {
      return;
    }
    handleSend(String(prompt));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [prompt]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await refetch();
    setRefreshing(false);
  };

  const handleSend = async (text?: string) => {
    const value = (text ?? input).trim();
    if (!value) {
      return;
    }
    const userMessage: AiChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: value,
      createdAt: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setSending(true);
    const result = await AiAssistantRepo.chat(value);
    setSending(false);
    if (!result.ok) {
      show({ message: result.error.displayMessage ?? '发送失败', type: 'error' });
      return;
    }
    setMessages((prev) => [...prev, result.data]);
    requestAnimationFrame(() => scrollRef.current?.scrollToEnd({ animated: true }));
  };

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="AI 农管家" />
      <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
        <View style={{ flex: 1 }}>
          <ScrollView
            ref={scrollRef}
            contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing['3xl'] }}
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
            onContentSizeChange={() => scrollRef.current?.scrollToEnd({ animated: true })}
          >
            <View style={styles.shortcutRow}>
              {shortcuts.map((item) => (
                <Pressable
                  key={item.id}
                  onPress={() => handleSend(item.prompt)}
                  style={[
                    styles.shortcutChip,
                    { backgroundColor: colors.brand.primarySoft, borderRadius: radius.pill },
                  ]}
                >
                  <Text style={[typography.caption, { color: colors.brand.primary }]}>{item.title}</Text>
                </Pressable>
              ))}
            </View>

            {messages.map((message) => {
              const isUser = message.role === 'user';
              return (
                <View
                  key={message.id}
                  style={[
                    styles.messageRow,
                    { justifyContent: isUser ? 'flex-end' : 'flex-start' },
                  ]}
                >
                  <View
                    style={[
                      styles.bubble,
                      {
                        backgroundColor: isUser ? colors.brand.primary : colors.surface,
                        borderColor: isUser ? colors.brand.primary : colors.border,
                        borderRadius: radius.lg,
                      },
                    ]}
                  >
                    <Text style={[typography.body, { color: isUser ? colors.text.inverse : colors.text.primary }]}>
                      {message.content}
                    </Text>
                  </View>
                </View>
              );
            })}

            {sending ? (
              <View style={[styles.messageRow, { justifyContent: 'flex-start' }]}>
                <View style={[styles.bubble, { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg }]}>
                  <Text style={[typography.caption, { color: colors.text.secondary }]}>AI 正在思考…</Text>
                </View>
              </View>
            ) : null}
          </ScrollView>

          <View style={[styles.inputBar, { borderTopColor: colors.border }]}>
            <TextInput
              value={input}
              onChangeText={setInput}
              placeholder="向 AI 农管家提问"
              placeholderTextColor={colors.text.secondary}
              style={[styles.input, { color: colors.text.primary }]}
            />
            <Pressable
              onPress={() => handleSend()}
              style={[styles.sendButton, { backgroundColor: colors.brand.primary, borderRadius: radius.pill }]}
            >
              <MaterialCommunityIcons name="send" size={16} color={colors.text.inverse} />
            </Pressable>
          </View>
        </View>
      </KeyboardAvoidingView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  shortcutRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  shortcutChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  messageRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  bubble: {
    maxWidth: '78%',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
  },
  inputBar: {
    borderTopWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  sendButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 8,
  },
});

// 交付包/uniapp/src/pages-sub/ai/chat.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="AI 农管家" />
    <view class="nm-container">
      <scroll-view
        class="nm-page"
        scroll-y
        scroll-with-animation
        :scroll-into-view="scrollIntoView"
        refresher-enabled
        :refresher-triggered="refreshing"
        @refresherrefresh="onRefresh"
      >
        <view class="nm-shortcuts">
          <view v-for="item in shortcuts" :key="item.id" class="nm-shortcut" @click="send(item.prompt)">
            <text class="nm-shortcut__text">{{ item.title }}</text>
          </view>
        </view>

        <view v-for="message in messages" :key="message.id" :id="message.id" class="nm-msg">
          <view :class="['nm-msg__bubble', message.role === 'user' ? 'nm-msg__bubble--user' : '']">
            <text class="nm-msg__text">{{ message.content }}</text>
          </view>
        </view>

        <view v-if="sending" id="ai-thinking" class="nm-msg">
          <view class="nm-msg__bubble">
            <text class="nm-msg__hint">AI 正在思考...</text>
          </view>
        </view>
      </scroll-view>

      <view class="nm-input-bar">
        <input
          v-model="input"
          class="nm-input"
          placeholder="向 AI 农管家提问"
          placeholder-class="nm-placeholder"
          confirm-type="send"
          @confirm="send()"
        />
        <view class="nm-send" @click="send()">
          <Icon name="send" :size="32" :color="textInverse" />
        </view>
      </view>
    </view>
  </Screen>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { Screen, AppHeader, Icon } from '@/components';
import { AiAssistantRepo } from '@/services/repos';
import type { AiChatMessage, AiShortcut } from '@/services/repos/ai-assistant';
import { useToast } from '@/components/feedback/useToast';

const textInverse = '#FFFFFF';
const input = ref('');
const messages = ref<AiChatMessage[]>([
  {
    id: 'ai-greeting',
    role: 'assistant',
    content: '你好，我是 AI 农管家。',
    createdAt: new Date().toISOString(),
  },
]);
const shortcuts = ref<AiShortcut[]>([]);
const refreshing = ref(false);
const sending = ref(false);
const scrollIntoView = ref('ai-greeting');
const toast = useToast();

const fetchShortcuts = async () => {
  const res = await AiAssistantRepo.listShortcuts();
  if (res.ok) {
    shortcuts.value = res.data;
  }
};

const onRefresh = () => {
  if (refreshing.value) return;
  refreshing.value = true;
  fetchShortcuts().finally(() => {
    refreshing.value = false;
  });
};

const send = async (text?: string) => {
  const value = (text ?? input.value).trim();
  if (!value) return;
  const userMsg: AiChatMessage = {
    id: `user-${Date.now()}`,
    role: 'user',
    content: value,
    createdAt: new Date().toISOString(),
  };
  messages.value = messages.value.concat(userMsg);
  input.value = '';
  scrollIntoView.value = userMsg.id;
  sending.value = true;
  const res = await AiAssistantRepo.chat(value);
  sending.value = false;
  if (res.ok) {
    messages.value = messages.value.concat(res.data);
    scrollIntoView.value = res.data.id;
  } else {
    toast.show({ message: res.error.message || '发送失败', type: 'error' });
    scrollIntoView.value = 'ai-thinking';
  }
};

onLoad((options?: Record<string, string>) => {
  fetchShortcuts();
  if (options?.prompt) {
    send(options.prompt);
  }
});
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-container {
  flex: 1;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.nm-page {
  flex: 1;
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-shortcuts {
  flex-direction: row;
  flex-wrap: wrap;
  margin-bottom: $nm-space-md;
}

.nm-shortcut {
  padding: 12rpx 24rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary-soft;
  margin-right: 16rpx;
  margin-bottom: 16rpx;
}

.nm-shortcut__text {
  font-size: $nm-font-caption;
  color: $nm-brand-primary;
}

.nm-msg {
  margin-bottom: 20rpx;
  flex-direction: row;
}

.nm-msg__bubble {
  max-width: 78%;
  padding: 20rpx 24rpx;
  border-radius: $nm-radius-lg;
  background-color: $nm-surface;
  border: 1rpx solid $nm-border;
}

.nm-msg__bubble--user {
  margin-left: auto;
  background-color: $nm-brand-primary;
  border-color: $nm-brand-primary;
}

.nm-msg__text {
  font-size: $nm-font-body;
  color: $nm-text-primary;
}

.nm-msg__bubble--user .nm-msg__text {
  color: $nm-text-inverse;
}

.nm-msg__hint {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-input-bar {
  flex-direction: row;
  align-items: center;
  padding: 16rpx 24rpx;
  border-top: 1rpx solid $nm-border;
  background-color: $nm-background;
  padding-bottom: calc(16rpx + env(safe-area-inset-bottom));
}

.nm-input {
  flex: 1;
  padding: 16rpx 24rpx;
  border-width: 0;
  background-color: transparent;
  font-size: $nm-font-body;
  color: $nm-text-primary;
}

.nm-placeholder {
  color: $nm-text-secondary;
}

.nm-send {
  margin-left: 16rpx;
  padding: 16rpx 24rpx;
  border-radius: $nm-radius-pill;
  background-color: $nm-brand-primary;
  align-items: center;
  justify-content: center;
}

</style>
