// 交付包/uniapp/src/pages-sub/me/inbox.vue
<template>
  <Screen :safeTop="true">
    <AppHeader title="消息中心" />
    <view class="nm-page">
      <view class="nm-toolbar">
        <view class="nm-tabs">
          <view
            v-for="tab in tabs"
            :key="tab.id"
            :class="['nm-tab', activeTab === tab.id ? 'nm-tab--active' : '']"
            @click="setTab(tab.id)"
          >
            <text :class="['nm-tab__text', activeTab === tab.id ? 'nm-tab__text--active' : '']">{{ tab.label }}</text>
          </view>
        </view>
        <view class="nm-filters">
          <view
            :class="['nm-filter', unreadOnly ? 'nm-filter--active' : '']"
            @click="toggleUnread"
          >仅未读</view>
          <view
            :class="['nm-filter', unreadCount === 0 ? 'nm-filter--disabled' : '']"
            @click="markAllRead"
          >全部已读</view>
        </view>
        <view class="nm-summary">
          <text class="nm-summary__text">{{ summaryText }}</text>
          <text v-if="hasFilter" class="nm-summary__link" @click="resetFilter">清空筛选</text>
        </view>
      </view>

      <view class="nm-list">
        <Skeleton v-if="loading" :count="2" type="card" />
        <ErrorState v-else-if="errorMessage" :text="errorMessage" @retry="fetchInbox(true)" />
        <view v-else-if="!loading && items.length === 0" class="nm-empty">
          <EmptyState :text="emptyText" :hint="emptyHint" />
          <view class="nm-empty__action" @click="handleEmptyAction">{{ emptyActionLabel }}</view>
        </view>
        <scroll-view v-else scroll-y refresher-enabled :refresher-triggered="refreshing" @refresherrefresh="onRefresh">
          <view v-for="item in items" :key="item.id" class="nm-item" @click="openDetail(item)">
            <view class="nm-item__icon" :class="iconTone(item)">
              <Icon :name="iconName(item)" :size="36" :color="iconColor(item)" />
            </view>
            <view class="nm-item__body">
              <view class="nm-item__title-row">
                <text class="nm-item__title" :lines="1">{{ item.title }}</text>
                <view v-if="item.unread" class="nm-item__dot" />
              </view>
              <text class="nm-item__desc" :lines="2">{{ item.desc }}</text>
              <text class="nm-item__time" :lines="1">{{ item.time }}</text>
            </view>
            <Icon class="nm-item__arrow" name="chevron-right" :size="40" :color="textSecondary" />
          </view>
        </scroll-view>
      </view>
    </view>
  </Screen>
</template>

<script setup lang="ts">
import { navTo, navTab } from '@/utils/nav';
import { computed, ref } from 'vue';
import { Screen, AppHeader, ErrorState, Skeleton, EmptyState, Icon } from '@/components';
import { InboxRepo, type InboxItem } from '@/services/repos';
import { InboxState } from '@/services/state';

const brandPrimary = '#2F8F4E';
const accentBlue = '#2B6CB0';
const textSecondary = '#4B5B53';
const tabs: Array<{ id: 'all' | '互动' | '交易' | '系统'; label: string }> = [
  { id: 'all', label: '全部' },
  { id: '互动', label: '互动' },
  { id: '交易', label: '交易' },
  { id: '系统', label: '系统' },
];

const activeTab = ref<'all' | '互动' | '交易' | '系统'>('all');
const unreadOnly = ref(false);
const items = ref<InboxItem[]>([]);
const loading = ref(false);
const refreshing = ref(false);
const errorMessage = ref('');

const unreadCount = computed(() => items.value.filter((item) => item.unread).length);
const hasFilter = computed(() => activeTab.value !== 'all' || unreadOnly.value);
const summaryText = computed(() => `${hasFilter.value ? '当前筛选' : '全部消息'} · 未读 ${unreadCount.value} 条`);
const emptyText = computed(() => (hasFilter.value ? '暂无匹配消息' : '暂无消息'));
const emptyHint = computed(() => (hasFilter.value ? '试试调整筛选条件' : '互动通知会出现在这里'));
const emptyActionLabel = computed(() => (hasFilter.value ? '清空筛选' : '去农脉圈'));

const fetchInbox = async (reset = true) => {
  loading.value = true;
  const res = await InboxRepo.list({
    page: 1,
    pageSize: 20,
    type: activeTab.value === 'all' ? '全部' : activeTab.value,
    unreadOnly: unreadOnly.value,
  });
  if (res.ok) {
    errorMessage.value = '';
    items.value = res.data.items;
    InboxState.refreshUnreadCount();
  } else {
    errorMessage.value = res.error.message || '加载失败';
  }
  loading.value = false;
  if (refreshing.value) refreshing.value = false;
};

const onRefresh = () => {
  if (refreshing.value) return;
  refreshing.value = true;
  fetchInbox(true);
};

const setTab = (tab: 'all' | '互动' | '交易' | '系统') => {
  activeTab.value = tab;
  fetchInbox(true);
};

const toggleUnread = () => {
  unreadOnly.value = !unreadOnly.value;
  fetchInbox(true);
};

const resetFilter = () => {
  activeTab.value = 'all';
  unreadOnly.value = false;
  fetchInbox(true);
};

const handleEmptyAction = () => {
  if (hasFilter.value) {
    resetFilter();
    return;
  }
  navTab({ url: '/pages/tabbar/circle/circle' });
};

const markAllRead = async () => {
  if (unreadCount.value === 0) {
    uni.showToast({ title: '暂无未读消息', icon: 'none' });
    return;
  }
  await InboxRepo.markAllRead();
  items.value = items.value.map((item) => ({ ...item, unread: false }));
  InboxState.setUnreadCount(0);
  uni.showToast({ title: '全部标为已读', icon: 'success' });
};

const openDetail = async (item: InboxItem) => {
  if (item.unread) {
    await InboxRepo.markRead(item.id);
    item.unread = false;
  }
  const params = [
    `id=${item.id}`,
    `title=${encodeURIComponent(item.title)}`,
    `desc=${encodeURIComponent(item.desc)}`,
    `time=${encodeURIComponent(item.time)}`,
    `type=${encodeURIComponent(item.type)}`,
    item.status ? `status=${encodeURIComponent(item.status)}` : '',
    item.actionType ? `actionType=${encodeURIComponent(item.actionType)}` : '',
  ]
    .filter(Boolean)
    .join('&');
  navTo({ url: `/pages-sub/me/interaction-detail?${params}` });
};

const ACTION_ICON_MAP: Record<NonNullable<InboxItem['actionType']>, { name: string; tone: 'brand' | 'accent' | 'neutral' }> = {
  expert: { name: 'comment-question-outline', tone: 'accent' },
  reward: { name: 'gift-outline', tone: 'brand' },
  coop: { name: 'handshake-outline', tone: 'accent' },
  group: { name: 'account-group-outline', tone: 'brand' },
  like: { name: 'heart-outline', tone: 'brand' },
  system: { name: 'bell-outline', tone: 'neutral' },
};

const TYPE_ICON_MAP: Record<InboxItem['type'], { name: string; tone: 'brand' | 'accent' | 'neutral' }> = {
  交易: { name: 'truck-delivery-outline', tone: 'brand' },
  互动: { name: 'comment-text-outline', tone: 'accent' },
  系统: { name: 'bell-outline', tone: 'neutral' },
};

const iconConfig = (item: InboxItem) => {
  if (item.actionType && ACTION_ICON_MAP[item.actionType]) {
    return ACTION_ICON_MAP[item.actionType];
  }
  return TYPE_ICON_MAP[item.type] ?? { name: 'bell-outline', tone: 'neutral' };
};

const iconName = (item: InboxItem) => iconConfig(item).name;

const iconTone = (item: InboxItem) => {
  const tone = iconConfig(item).tone;
  if (tone === 'brand') return 'nm-item__icon--brand';
  if (tone === 'accent') return 'nm-item__icon--accent';
  return 'nm-item__icon--neutral';
};

const iconColor = (item: InboxItem) => {
  const tone = iconConfig(item).tone;
  if (tone === 'brand') return brandPrimary;
  if (tone === 'accent') return accentBlue;
  return textSecondary;
};

fetchInbox(true);
</script>

<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;

.nm-page {
  padding: $nm-space-xl;
  padding-bottom: $nm-space-3xl;
}

.nm-toolbar {
  margin-bottom: $nm-space-md;
}

.nm-tabs {
  flex-direction: row;
  flex-wrap: wrap;
  margin-bottom: 16rpx;
}

.nm-tab {
  padding: 12rpx 24rpx;
  border-radius: $nm-radius-pill;
  border: 1rpx solid $nm-border;
  margin-right: 16rpx;
  margin-bottom: 16rpx;
}

.nm-tab--active {
  border-color: $nm-brand-primary;
  background-color: $nm-brand-primary-soft;
}

.nm-tab__text {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-tab__text--active {
  color: $nm-brand-primary;
  font-weight: 600;
}

.nm-filters {
  flex-direction: row;
}

.nm-filter {
  padding: 12rpx 24rpx;
  border-radius: $nm-radius-pill;
  border: 1rpx solid $nm-border;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
  margin-right: 16rpx;
}

.nm-filter--active {
  border-color: $nm-accent-blue;
  background-color: $nm-accent-blue-soft;
  color: $nm-accent-blue;
}

.nm-filter--disabled {
  opacity: 0.5;
}

.nm-summary {
  margin-top: $nm-space-sm;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
}

.nm-summary__text {
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-summary__link {
  padding: 8rpx 12rpx;
  font-size: $nm-font-caption;
  color: $nm-accent-blue;
}

.nm-empty {
  margin-top: $nm-space-md;
}

.nm-empty__action {
  margin-top: $nm-space-sm;
  padding: 10rpx 16rpx;
  border-radius: $nm-radius-pill;
  border: 1rpx solid $nm-border;
  align-self: center;
  font-size: $nm-font-caption;
  color: $nm-text-secondary;
}

.nm-item {
  padding: $nm-space-md 0;
  border-bottom: 1rpx solid $nm-border;
  display: flex;
  flex-direction: row;
  align-items: center;
}

.nm-item__icon {
  width: 72rpx;
  height: 72rpx;
  border-radius: $nm-radius-pill;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 20rpx;
}

.nm-item__icon--brand {
  background-color: $nm-brand-primary-soft;
}

.nm-item__icon--accent {
  background-color: $nm-accent-blue-soft;
}

.nm-item__icon--neutral {
  background-color: $nm-border;
}

.nm-item__body {
  flex: 1;
  margin-right: 16rpx;
}

.nm-item__title-row {
  display: flex;
  flex-direction: row;
  align-items: center;
}

.nm-item__title {
  font-size: $nm-font-body;
  line-height: $nm-line-body;
  font-weight: 600;
  color: $nm-text-primary;
}

.nm-item__dot {
  width: 12rpx;
  height: 12rpx;
  border-radius: 999rpx;
  background-color: $nm-danger;
  margin-left: 12rpx;
}

.nm-item__desc {
  margin-top: 8rpx;
  font-size: $nm-font-caption;
  line-height: $nm-line-caption;
  color: $nm-text-secondary;
}

.nm-item__time {
  margin-top: 12rpx;
  font-size: $nm-font-caption;
  line-height: $nm-line-caption;
  color: $nm-text-secondary;
}

.nm-item__arrow {
  flex-shrink: 0;
}
</style>

// app/inbox/index.tsx
import React, { useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AppHeader, Screen } from '../../src/components/layout';
import { EmptyState, ErrorState, Skeleton, useToast } from '../../src/components/feedback';
import { InboxRepo } from '../../src/repos';
import { useAuthStore } from '../../src/store';
import { useTheme } from '../../src/theme';
import { AppError, InboxCategory, InboxMessage, InboxType } from '../../src/types';
import { resolveBuyerNotificationRoute } from '../../src/utils/notificationRoutes';

type InboxTab = 'all' | InboxCategory;

const iconMap: Partial<Record<InboxType, { name: string; tone: 'brand' | 'accent' | 'neutral' }>> = {
  expert_reply: { name: 'comment-question-outline', tone: 'accent' },
  tip_paid: { name: 'gift-outline', tone: 'brand' },
  cooperation_update: { name: 'handshake-outline', tone: 'accent' },
  like: { name: 'heart-outline', tone: 'brand' },
  comment: { name: 'comment-text-outline', tone: 'brand' },
  follow: { name: 'account-plus-outline', tone: 'accent' },
  order_update: { name: 'truck-delivery-outline', tone: 'brand' },
  booking_update: { name: 'calendar-check-outline', tone: 'accent' },
  // C12: 钱相关事件
  reward_credited: { name: 'cash-plus', tone: 'brand' },
  reward_unfrozen: { name: 'lock-open-outline', tone: 'brand' },
  reward_expired: { name: 'clock-alert-outline', tone: 'neutral' },
  withdraw_approved: { name: 'bank-transfer-out', tone: 'brand' },
  withdraw_rejected: { name: 'bank-remove', tone: 'accent' },
  vip_referral_bonus: { name: 'account-star-outline', tone: 'brand' },
  refund_credited: { name: 'cash-refund', tone: 'accent' },
  coupon_granted: { name: 'ticket-percent-outline', tone: 'brand' },
  coupon_expired: { name: 'ticket-outline', tone: 'neutral' },
  // 卖家/系统通知
  new_order: { name: 'package-variant', tone: 'brand' },
  stock_shortage: { name: 'alert-circle-outline', tone: 'accent' },
  vip_activated: { name: 'crown-outline', tone: 'brand' },
  order_receiver_info_required: { name: 'map-marker-alert-outline', tone: 'accent' },
};

export default function InboxScreen() {
  const { colors, radius, spacing, typography, shadow } = useTheme();
  const { show } = useToast();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState<InboxTab>('all');
  const [unreadOnly, setUnreadOnly] = useState(false);
  const isLoggedIn = useAuthStore((state) => state.isLoggedIn);

  const { data, isLoading, isFetching, refetch } = useQuery({
    queryKey: ['inbox', activeTab, unreadOnly],
    queryFn: () => InboxRepo.list(activeTab === 'all' ? undefined : activeTab, unreadOnly),
    enabled: isLoggedIn,
  });

  const listError = data && !data.ok ? data.error : null;
  const messages = data?.ok ? data.data : [];
  const hasFilter = activeTab !== 'all' || unreadOnly;
  const unreadCount = messages.filter((message) => message.unread).length;

  const tabs = useMemo(
    () => [
      { id: 'all', label: '全部' },
      { id: 'interaction', label: '互动' },
      { id: 'transaction', label: '交易' },
      { id: 'system', label: '系统' },
    ],
    []
  );

  const invalidateInboxState = async () => {
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['inbox'] }),
      queryClient.invalidateQueries({ queryKey: ['me-inbox-unread'] }),
    ]);
  };

  const handleOpenMessage = async (message: InboxMessage) => {
    if (message.unread) {
      const result = await InboxRepo.markRead(message.id);
      if (!result.ok) {
        show({ message: result.error.displayMessage ?? '操作失败', type: 'error' });
        return;
      }
      await invalidateInboxState();
    }

    const route = resolveBuyerNotificationRoute(message.action ?? message.target);
    if (route) {
      router.push(route as any);
      return;
    }

    show({ message: '该消息暂无可跳转的页面', type: 'info' });
  };

  // 判断单条消息是否可点击跳转，用于 chevron 条件渲染
  const isMessageClickable = (message: InboxMessage): boolean =>
    resolveBuyerNotificationRoute(message.action ?? message.target) !== null;

  return (
    <Screen contentStyle={{ flex: 1 }}>
      <AppHeader title="消息中心" />
      <View style={{ padding: spacing.xl, paddingBottom: spacing['3xl'], flex: 1 }}>
        <View style={styles.toolbar}>
          <View style={styles.tabRow}>
            {tabs.map((tab) => {
              const active = tab.id === activeTab;
              return (
                <Pressable
                  key={tab.id}
                  onPress={() => setActiveTab(tab.id as InboxTab)}
                  style={[
                    styles.tabChip,
                    {
                      overflow: 'hidden',
                      borderColor: active ? colors.brand.primary : colors.border,
                      borderRadius: radius.pill,
                    },
                  ]}
                >
                  {active ? (
                    <LinearGradient
                      colors={[colors.brand.primarySoft, colors.ai.soft]}
                      start={{ x: 0, y: 0 }}
                      end={{ x: 1, y: 0 }}
                      style={StyleSheet.absoluteFill}
                    />
                  ) : null}
                  <Text style={[typography.caption, { color: active ? colors.brand.primary : colors.text.secondary }]}>
                    {tab.label}
                  </Text>
                </Pressable>
              );
            })}
          </View>
          <View style={styles.filterRow}>
            <Pressable
              onPress={() => setUnreadOnly((prev) => !prev)}
              style={[
                styles.filterChip,
                {
                  borderColor: unreadOnly ? colors.accent.blue : colors.border,
                  backgroundColor: unreadOnly ? colors.accent.blueSoft : colors.surface,
                  borderRadius: radius.pill,
                },
              ]}
            >
              <Text style={[typography.caption, { color: unreadOnly ? colors.accent.blue : colors.text.secondary }]}>
                仅未读
              </Text>
            </Pressable>
            <Pressable
              onPress={async () => {
                if (unreadCount === 0) {
                  show({ message: '暂无未读消息', type: 'info' });
                  return;
                }
                const result = await InboxRepo.markAllRead();
                if (!result.ok) {
                  show({ message: result.error.displayMessage ?? '操作失败', type: 'error' });
                  return;
                }
                show({ message: '全部标为已读', type: 'success' });
                await invalidateInboxState();
              }}
              disabled={unreadCount === 0}
              style={[
                styles.filterChip,
                {
                  borderColor: colors.border,
                  borderRadius: radius.pill,
                  opacity: unreadCount === 0 ? 0.5 : 1,
                },
              ]}
            >
              <Text style={[typography.caption, { color: colors.text.secondary }]}>全部已读</Text>
            </Pressable>
          </View>
          <View style={styles.summaryRow}>
            <Text style={[typography.caption, { color: colors.text.secondary }]}>
              {hasFilter ? '当前筛选' : '全部消息'} · 未读 {unreadCount} 条
            </Text>
            {hasFilter ? (
              <Pressable
                onPress={() => {
                  setActiveTab('all');
                  setUnreadOnly(false);
                }}
                style={styles.resetFilter}
              >
                <Text style={[typography.caption, { color: colors.accent.blue }]}>清空筛选</Text>
              </Pressable>
            ) : null}
          </View>
        </View>

        {isLoading ? (
          <View>
            <Skeleton height={120} radius={radius.lg} />
            <View style={{ height: spacing.md }} />
            <Skeleton height={120} radius={radius.lg} />
          </View>
        ) : (listError as AppError | null) ? (
          <ErrorState
            title="消息加载失败"
            description={listError?.displayMessage ?? '请稍后重试'}
            onAction={refetch}
          />
        ) : messages.length === 0 ? (
          <EmptyState
            title={hasFilter ? '暂无匹配消息' : '暂无消息'}
            description={hasFilter ? '试试调整筛选条件' : '互动通知会出现在这里'}
            actionLabel={hasFilter ? '清空筛选' : '去首页'}
            onAction={() => {
              if (hasFilter) {
                setActiveTab('all');
                setUnreadOnly(false);
                return;
              }
              router.push('/(tabs)/home');
            }}
          />
        ) : (
          <ScrollView
            refreshControl={<RefreshControl refreshing={isFetching} onRefresh={refetch} />}
            showsVerticalScrollIndicator={false}
          >
            {messages.map((message, msgIndex) => {
              const icon = iconMap[message.type] ?? { name: 'bell-outline', tone: 'neutral' };
              const iconColor =
                icon.tone === 'brand'
                  ? colors.brand.primary
                  : icon.tone === 'accent'
                  ? colors.accent.blue
                  : colors.text.secondary;
              const iconBg =
                icon.tone === 'brand'
                  ? colors.brand.primarySoft
                  : icon.tone === 'accent'
                  ? colors.accent.blueSoft
                  : colors.border;
              return (
                <Animated.View key={message.id} entering={FadeInDown.duration(300).delay(50 + msgIndex * 30)}>
                  <Pressable
                    onPress={() => handleOpenMessage(message)}
                    style={[styles.messageRow, shadow.md, { backgroundColor: colors.surface, borderRadius: radius.lg, marginBottom: 8, padding: 12 }]}
                  >
                    <View style={[styles.iconWrap, { backgroundColor: iconBg }]}>
                      <MaterialCommunityIcons name={icon.name as any} size={18} color={iconColor} />
                    </View>
                    <View style={styles.messageInfo}>
                      <View style={styles.messageHeader}>
                        <Text style={[typography.bodyStrong, { color: colors.text.primary }]} numberOfLines={1}>
                          {message.title}
                        </Text>
                        {message.unread ? <View style={[styles.dot, { backgroundColor: colors.danger }]} /> : null}
                      </View>
                      <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 4 }]} numberOfLines={2}>
                        {message.content}
                      </Text>
                      <Text style={[typography.caption, { color: colors.text.secondary, marginTop: 6 }]}>
                        {message.createdAt}
                      </Text>
                    </View>
                    {/* 仅当消息可跳转时显示 chevron，info-only 消息不显示避免误导 */}
                    {isMessageClickable(message) ? (
                      <MaterialCommunityIcons name="chevron-right" size={20} color={colors.text.secondary} />
                    ) : null}
                  </Pressable>
                </Animated.View>
              );
            })}
          </ScrollView>
        )}
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  toolbar: {
    marginBottom: 12,
  },
  tabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  tabChip: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  filterRow: {
    flexDirection: 'row',
  },
  filterChip: {
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  resetFilter: {
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  messageInfo: {
    flex: 1,
    marginRight: 8,
  },
  messageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginLeft: 6,
  },
});
